### ISSUE TITLE
Queries with "include" are very inefficient

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback-connector-mysql#104]
Suppose I have three tables

```
User
--------
user_id
firstname
lastname

Car
--------
car_id
user_id
color_id
name

Color
--------
color_id
name
```

If I run the query: 

```
User.find({
  include: [{car: 'color'}]
}, function(err, user) {});
```

I would expect it to execute a single query that joins all three tables and massages the data correspondingly into a JSON structure. However, when logging the mysql queries I see that this will perform a separate query for each color that belongs to the car.

This seems very inefficient and slow depending on your data.

**Comment by csvan** [comment]
+1, this is a huge performance drain, especially for queries over large datasets.

**Comment by richardaum** [comment]
+1

http://stackoverflow.com/questions/34598531/exclude-items-from-first-level-filter-when-children-levels-are-empty-at-loopback
^ This problem may be caused because of this implementation.

**Comment by nicktee89** [comment]
Is this fix and released in 2.2.1?

**Comment by jaime-franco** [comment]
+1

**Comment by regevbr** [comment]
Can't believe this wasn't fixed yet...

**Comment by Amir-61** [comment]
I'm not on LoopBack project anymore; however you may see @kjdelisle's comment in this regard: https://github.com/strongloop/loopback/issues/683#issuecomment-322298462
