### ISSUE TITLE
Master/Slave support?

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback-connector-mysql#105]
Upon initial inspection of the code it looks like master/slave configuration support is not handled by this mysql connector. Is this correct? If so, can it be a feature request?

**Comment by violet-day** [comment]
+1

**Comment by smartmouse** [comment]
That will be useful , but just curious, How will this Master/slave configuration be supported in your opinion?   What capabilities/features are you looking for in particular from the connector?  e.g. To be able to create and support master/slave configuration,  connect in the failover cases and execute queries etc. seemlessly?  Or allow read/write in the load balancing cases over multiple dataabse servers?

**Comment by stringbeans** [comment]
@smartmouse the support im thinking of would be the following (in our case for the mysql connector):

1. be able to define a master connection
2. define multiple slave connections
3. have the queries default to slave for all non-mutative commands (ie. only SELECTS)
4. have mutative queries default to master (UPDATE/DELETE/INSERT)
5. support an optional param in model methods to force the query to go to either master/slave

I've noticed that the model api is very similar to sequelize. If you take a look at how sequelize handles master/slave support you'll get a good idea of what should be provided by loopback.

**Comment by smartmouse** [comment]
@stringbeans Thanks for the info. We will do some research first and put in the backlog for offering Manager to decide/prioritize.  If you come across any good ideas, please do comment here, will be more than happyt o check it out.  I will definitely check out sequelize.

**Comment by haotangio** [comment]
I don't think this connector need to support the master-slave config.

Simply put, this is just an ORM, master-slave or any high availability settings should be operation & deployment concern, not development concern.

How do you think?

**Comment by jshanman** [comment]
@haotangio I disagree.  When developing against a high availability cluster, it is often necessary to indicate that certain queries should be against the master while allowing other queries to default to potentially lagged replicated readers.  For example, if you run an update statement (which should be directed to the master of course), then attempt to read that update immediately, if replication is lagged slightly, then you will not get the updated row but instead will get the outdated row.  Sequelize and many other ORM's in different languages I've used allow sending 'useMaster' as a query option in this case.  

It is also useful to be able to have one or more connection pools to point to read-only hosts and another separate connection pool to point to the write host.  This would enable support of several types of mysql cluster configurations.

See https://github.com/sequelize/sequelize/blob/2fc43c4cd1efe7f0ba649a7d6572119502fb0a42/lib/dialects/abstract/connection-manager.js#L239 for an example of how it is done in sequelize.

**Comment by stringbeans** [comment]
thanks @jshanman i was about to reply with a similar response. there are ways around the update-read situation by using transactions, but that could just introduce unnecessary complexity. 

this is perhaps a segway into another discussion but is there any reason why loopback does not just use an already available off-the-shelf ORM? that way loopback doesn't need to reinvent the wheel when it comes to an ORM for specific datasources but only maintain the juggler

**Comment by jshanman** [comment]
@haotangio can you see my and @stringbeans comments and let us know if this will ever get on the roadmap?

**Comment by haotangio** [comment]
@jshanman I understood your idea now. Loopback should consider supporting it. Btw, I agree with @stringbeans about using currently available ORM instead of re-invent the code.

Looks like loopback team do not take care of Github issues so actively these days. A lot of issues were auto-closed.

**Comment by arpitdawar79** [comment]
any update on this issue
