### ISSUE TITLE
discoverSchema does not discover enum members

### ISSUE THREAD

**Issue by mrkswrnr** [strongloop/loopback-connector-mysql#111]
I have a MySQL database table containing an enum field: 
```
CREATE TABLE `customer` (
  ...
  `type` enum('WEB','USER') NOT NULL DEFAULT 'USER',
  ...
);
```
When using discoverSchema the resulting property definition looks like:
```
"type": {
      "type": "String",
      "required": true,
      "length": 6,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "type",
        "dataType": "enum",
        "dataLength": 6,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "N"
      }
    },
```
which leads to an error when trying to automigrate the table.

Currently I manually set ```mysql.dataLength``` to ```"'WEB', 'USER'" ``` to fix this but it would be great to have discoverSchema generate the right data.

**Comment by loay** [comment]
@mrkswrnr 
We are currently working on this issue. The feature should be available very soon. 
Thanks.

**Comment by loay** [comment]
@mrkswrnr 
There is a branch called `Enum` if you want to test it. 
We are doing the final touches and it will be released soon. 
Regards.

**Comment by mrkswrnr** [comment]
@loay 
Thank you! Works for our mysql environment though we switched to postgres a while ago :)
