### ISSUE TITLE
Support default value in migrations and discovery

### ISSUE THREAD

**Issue by mrkswrnr** [strongloop/loopback-connector-mysql#112]
Currently `COLUMN_DEFAULT` of `information_schema.columns` is being ignored in discovery. Also there is no migration-metadata being created as in [loopback-connector-postgresql](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L437).

**Comment by PaddyMann** [comment]
Frustratingly the postgresql connector supports dbDefault and the mysql connector does not.

The most common use-case for a default value is timestamping:

    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updatedAt TIMESTAMP NULL DEFAULT DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP

Without this, we have to resort to creating mixins for setting the timestamps. Well then, there's a simple workaround you say! Not so, the recommended https://github.com/clarkbw/loopback-ds-timestamp-mixin hasn't managed to find a solution that works with validateUpsert: true (which is a must-have for many projects).

This DB setting should be simple and is instead costing a ridiculous amount of time and hair pulling, so would love to see it added :)

**Comment by shaheero** [comment]
Anyone reached a good workaround yet?

**Comment by jannyHou** [comment]
This feature should be similar to function [`columnDbDefault`](https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js#L507) in postgresql.

**Comment by b-admike** [comment]
Tracked in https://github.com/strongloop/loopback-connector-mysql/issues/320.
