### ISSUE TITLE
Date type filed saving problems

### ISSUE THREAD

**Issue by daddybh** [strongloop/loopback-connector-mysql#120]
Hi, I am wondering there is any way not to convert `Date` filed to UTC format?

Because there are some sql query in my system, and it would come to a inconsistency of the timezone.

I tried to add a `timezone` parameter in datasource configuration, but it  didnot take any affect.

**Comment by xiangmeng4geo** [comment]
I met the same problem.   
I found the code at 
<code>node_modules/loopback-connector-mysql/lib/mysql.js</code>
<code> line 253: return val.getFullUTCYear()......</code>
<code> line 353:val = new Date(val.toString().replace(/GMT.*$/, 'GMT'));</code>
I think it is a problem to handle  time zone like this,so I remove the UTC at line 253 and comment the line 353 .

**Comment by daddybh** [comment]
@xiangmeng4geo you can put a `"dateStrings": true` in  you datasource.json file. It will solve the problem and without change the source code.

**Comment by xiangmeng4geo** [comment]
@daddybh Oh,Thank you very much.

**Comment by bbito** [comment]
Another big thanks to @daddybh!
After going over LB's MySQL Connector Docs: https://docs.strongloop.com/display/public/LB/MySQL+connector , I didn't find anything about a dateStrings option this until finding this issue and taking the next step to the node-mysql github where the dateStrings option is described: https://github.com/felixge/node-mysql#connection-options as follows:

> dateStrings: Force date types (TIMESTAMP, DATETIME, DATE) to be returned as strings rather then inflated into JavaScript Date objects. (Default: false)

**Comment by jannyHou** [comment]
@xiangmeng4geo @daddybh As @bbito mentioned, this issue is a same one as https://github.com/strongloop/loopback-connector-mysql/issues/149
Shall we close this one and keep our discussion under issue#149? More people are involved there, easier for us to track the appropriate solutions. Thanks.
