### ISSUE TITLE
max_user_connections limit 

### ISSUE THREAD

**Issue by eugenehp** [strongloop/loopback-connector-mysql#122]
Hey folks,

Is there a way to set a limit of concurrent connections of the pool?

I'm getting this error when I use grunt automigrate tool (calling for autoupdate):
```
>> Error: ER_USER_LIMIT_REACHED: 
User 'bd28932a452f51' has exceeded the 'max_user_connections' resource 
(current value: 10)
```

Thank you.

Regards,
Eugene

**Comment by superkhau** [comment]
Where are you seeing this? Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by raymondfeng** [comment]
You should configure `connectionLimit` for your MySQL data source. For example,
```json
"mySQL": {
  "connector": "mysql",
  "host": "localhost",
  "connectionLimit": 32
}
```

**Comment by tkrugg** [comment]
for some reason when using the `url` property (instead of `host`, `username`, etc.) loopback is ignoring `connectionLimit`

**Comment by xinbenlv** [comment]
I am seeing this ignoring the limit too

**Comment by xinbenlv** [comment]
I dig into the code, and here is what i found.
If you look at [this file](https://github.com/strongloop/loopback-connector-mysql/blob/28d63b8dca65fd2d55408d747de68ad4605dd9cf/lib/mysql.js) you will find that 

It is ignoring the connectionLimit and other options if url is provided.
I am going to submit a pull request to fix this.

```javascript
  var options;
  if (s.url) {
    // use url to override other settings if url provided
    options = s.url;
  } else {
    options = {
      host: s.host || s.hostname || 'localhost',
      port: s.port || 3306,
      user: s.username || s.user,
      password: s.password,
      timezone: s.timezone,
      socketPath: s.socketPath,
      charset: s.collation.toUpperCase(), // Correct by docs despite seeming odd.
      supportBigNumbers: s.supportBigNumbers,
      connectionLimit: s.connectionLimit,
    };
```

**Comment by xinbenlv** [comment]
@tkrugg actually, I found that you can add "connectionLimit" to the url directly like this 
https://github.com/mysqljs/mysql/blob/master/test/unit/test-PoolConfig.js?line=33#L33
