### ISSUE TITLE
MariaDB+XtraDB compatible?

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback-connector-mysql#123]
Are there any known caveats associated with using this connector to work with MariaDB+XtraDB as opposed to vanilla MySQL+InnoDB? Both Maria and Xtra are forks of their respective counterparts, and designed to be drop-in replacements. Still, it would be good to know if there are any known collision areas.

**Comment by superkhau** [comment]
We do not officially support MariaDB. Please let us know if you decide to try it and if you run into any issues. We can resolve it then.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
