### ISSUE TITLE
can i generate datasource direct from db?

### ISSUE THREAD

**Issue by tushariscoolster** [strongloop/loopback-connector-mysql#124]
I have existing database, i want datasource to be generate directly from that db. So no need to define model, it will create dynamically, is it possible?

**Comment by raymondfeng** [comment]
https://docs.strongloop.com/display/APIS/Discovering+models+from+a+database

**Comment by donny08** [comment]
Hey raymondfeng,

I have tried you link for automatically creating models but issue is it doesn't create the relationship between models automically.How do i do that?

**Comment by tushariscoolster** [comment]
@raymondfeng ?? I too waiting for above anwser?

**Comment by raymondfeng** [comment]
Unfortunately, StrongLoop Arc doesn't expose the flag to discover relations. The dataSource.discoverSchemas() api has `options.relations` to express the need to follow relations.

**Comment by donny08** [comment]
In discover.Schema method,options.relations  is not working.

**Comment by donny08** [comment]
@raymondfeng Any Updates regarding my issue
