### ISSUE TITLE
Can't find HasMany relation option in Relation type when building realtionships after running slc loopback:relation

### ISSUE THREAD

**Issue by donny08** [strongloop/loopback-connector-mysql#127]
I ran slc loopback:relation -> Select the model to create the relationship from:model ->Relation type
in relation type i find > has many,  belongs to,  has and belongs to many and   has one types only wat abt HasManyThrough relation type

**Comment by donny08** [comment]
Its possible usig has many type by selection otions:-require through model[y/N]:yes

**Comment by superkhau** [comment]
@donny08 Are you still running into issues? Can you list the exact steps you're performing?

**Comment by donny08** [comment]
@superkhau Issue i'm facing is that i am unable to build automatic relationships between models in strongloop  after importing the existing db from mysql.
description:
I have three tables in a database: categories, company and categories-company (which has foreign keys of the categories and company tables).

I have done importing of tables via slc arc cmd but when I'm trying to discover/generate relationships using the discoverSchema method it generates only belongsto relation type for categories-company table and empty relationship i.e relation :{} for categories and company table

**Comment by superkhau** [comment]
@donny08 I don't believe we support discovery of relations. @raymondfeng Can you confirm?

@crandmck Do we have docs for discovery and how it effects relations?

**Comment by superkhau** [comment]
@donny08 Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by crandmck** [comment]
> Do we have docs for discovery and how it effects relations?

No, we don't have anything on that.  Most of what we have on discovery is in https://docs.strongloop.com/display/LB/Discovering+models+from+relational+databases.
AFAIK, relations are not included in discovery, but it may be DB-dependent.
@raymondfeng should confirm.

**Comment by superkhau** [comment]
@raymondfeng Do we support discovering relations?

**Comment by ssh24** [comment]
@donny08 You can use `db.discoverAndBuildModels` function to discover the relationships passing it down as a flag **relations: true**.

```js
db.discoverAndBuildModels({relations: true}, cb);
```

Please refer to the [apidocs](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverandbuildmodels) for more information.

Closing this issue as resolved. Feel free to reopen if needed.
