### ISSUE TITLE
Why id: true don't add auto_increment to field?

### ISSUE THREAD

**Issue by qvantor** [strongloop/loopback-connector-mysql#129]
Why id: true don't add auto_increment to field,
and how add auto increment?

**Comment by tngan** [comment]
@qvantor How did you solve the problem ?

**Comment by adcoolguy** [comment]
Did you use automigrate (which might overwrite the AUTO_INCREMENT property)? Our workaround that works was not to use automigrate but use only autoupdate and let the database schema changes not done by LoopBack UI like ARC. Furthermore, we set the model’s field required to false (letting the datastore handle the sequence/Id itself and not handled by the application/client/LoopBack).

HTH
