### ISSUE TITLE
destroyAll() not working with transactions

### ISSUE THREAD

**Issue by EmileSpecs** [strongloop/loopback-connector-mysql#131]
I added a relationship to the built-in User model:

```
User.hasMany(app.models.Task, { as: 'tasks', foreignKey: 'userId' });
```

Basically a User can have many Tasks associated with them.

When a User gets deleted I also delete some additional data associated with the User including their Tasks.

I use a transaction to make sure I can retain data integrity should anything go wrong. Deleting the User's Tasks using the transaction however doesn't work (these are two of the actions in my async auto):

```
tasks: ['transaction', 'user', function(callback, results) {
                results.user.tasks.destroyAll({ transaction: results.transaction }, callback);
            }],
            rolemapping: ['transaction', 'user', function(callback, results) {
                results.user.rolemapping.destroy({ transaction: results.transaction }, callback);
            }]
```

The transaction works for the RoleMapping `destroy()`, but not the Tasks `destroyAll()`...

Get the following error:

```
TypeError: val.replace is not a function
    at Object.SqlString.escape (<path>\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\SqlString.js:46:13)
```

Seems to me like the `destroyAll()` isn't expecting a transaction parameter and thinks it's SQL parameters which it then can't process.

From the docs transactions should work for `destroyAll()`?

**Comment by raymondfeng** [comment]
Try results.user.tasks.destroyAll({}, { transaction: results.transaction }, callback);

**Comment by jannyHou** [comment]
@EmileSpecs have you tried https://github.com/strongloop/loopback-connector-mysql/issues/131#issuecomment-159359198 from Raymond? Any update?

**Comment by EmileSpecs** [comment]
@jannyHou yes, Raymond's solution worked thanks! It's a long time ago but I think the parameters required were just not documented properly...
