### ISSUE TITLE
When Model not found request never resolves

### ISSUE THREAD

**Issue by EmileSpecs** [strongloop/loopback-connector-mysql#132]
When you query a model with values that would lead to it not finding any data the request never seems to resolve. Eventually after about 3 minutes my request times out.

So using the built-in User model if you query `Users/5` which doesn't exist you'll get:
```
{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "Unknown \"User\" id \"5\".",
    "statusCode": 404,
    "code": "MODEL_NOT_FOUND",
    "stack": "Error: Unknown \"User\" id \"5\".\n......"
  }
}
```
This is fine although returning an empty array would seem more logical to me.

The issue is when you query `Users` using this filter:
```
{ "where": {"id":5}}
```
The query never resolves and eventually just times out.

So this is just an example but the practical issue for example would come in when you're filtering data and no data matches the filter criteria, then you just don't get a response back...

Any help would be appreciated!

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by EmileSpecs** [comment]
Ah, my error!

I had some middleware that would also return the count of rows that didn't handle the empty response array properly...
