### ISSUE TITLE
Swagger: skipping unknown type "Text" on autoupdate().

### ISSUE THREAD

**Issue by notbrain** [strongloop/loopback-connector-mysql#133]
And also "text". Can't seem to track down where this is coming from, as there are no capital Text columns anywhere in our mysql schema. The lowercase text is warranted, since I just changed a bunch of columns to type: "text" in model.json files, but can't figure out where the "Text" is coming from.

I had originally reworked these field properties with mysql.dataType: "TEXT" but then found that that method was not very stable, and would use different column types based on the dataLength property, when all the text blob types are a certain max size by default. mysql.dataType:"TEXT" without any dataLength actually creates a VARCHAR(512). Spent some time with the code here and see why, but the Swagger thing was a bit of a concern after updating our loopback boot stuff.

**Comment by jannyHou** [comment]
@notbrain Seems this is the answer:
See [function buildColumnType](https://github.com/strongloop/loopback-connector-mysql/blob/37bb679f6e5527651d98bf1e9cdb25693ef799f9/lib/migration.js#L501-L512)

Default type is `text`.

**Comment by jannyHou** [comment]
And are you still run into same issue? If yes please fork https://github.com/strongloop/loopback-sandbox and provide your use case. I can help debug.

**Comment by ssh24** [comment]
You can specify the specific mysql column type for a particular field in the swagger definition. And upon `autoupdate/automigrate`, it will create the table column with that explicit datatype. 

Here is an example code snippet:

**model-definition.json**
```json
{
  "name": "League",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true,
      "mysql": {
        "dataType": "TEXT"
      }
    },
    "teams": {
      "type": [
        "string"
      ]
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var assert = require('assert');
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
  var db = app.dataSources.mysqlDs;

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('\nAutomigrate complete');
  });
};
```

**database output**
```bash
mysql> describe League;
+-------+---------+------+-----+---------+----------------+
| Field | Type    | Null | Key | Default | Extra          |
+-------+---------+------+-----+---------+----------------+
| id    | int(11) | NO   | PRI | NULL    | auto_increment |
| name  | text    | NO   |     | NULL    |                |
| teams | text    | YES  |     | NULL    |                |
+-------+---------+------+-----+---------+----------------+
3 rows in set (0.01 sec)
```

Closing this as the issue has been resolved. Feel free to reopen if needed.
