### ISSUE TITLE
Add auto creation of foreign keys to autoupdate and automigrate

### ISSUE THREAD

**Issue by kiraLinden** [strongloop/loopback-connector-mysql#135]
See https://github.com/strongloop/loopback-connector-mysql/issues/16 automigate and autoupdate currently don't create foreign keys, and it would be nice to have for referential integrity.

**Comment by XinV** [comment]
Up vote for this issue, it seems against the claim of serving as an enterprise framework if not having such referential integrity in place @raymondfeng @bajtos

**Comment by bajtos** [comment]
+1

**Comment by nautskye** [comment]
Yes please!

**Comment by remkohdev** [comment]
Is this still the case or am I misreading this? that when I have a 'built-in User' model with a relation 'hasMany' to my custom 'myObject', which works like a charm in memory db, that this relation is not 'automigrated' to a relational DB like PostGres, but that I have to code the extra foreign key field and maintain the relationship by explicitly saving it in my create/update and add it possibly to my delete and find filters? 
It would be super nice if it would automigrate it ofcourse, but the least that could be done, is document this properly perhaps?

**Comment by kiraLinden** [comment]
There's a way to manually do it https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-defineforeignkey but having it done without having to do that extra step would be nice.

**Comment by antonsamper** [comment]
@kiraLinden I have tried using `dataSource.defineForeignKey(className, key, foreignClassName, pkName)` but this doesn't explicitly set a field as a foreign key in the database.

**Comment by kiraLinden** [comment]
Oh sorry. This should probably be looked at by the loopback team...

**Comment by pluswave** [comment]
+1

**Comment by ferryhinardi** [comment]
+1

**Comment by antonsamper** [comment]
@bajtos do you know if there has been any progress with this issue?

**Comment by bajtos** [comment]
@antonsamper no progress so far. Would you like to contribute this feature yourself? We can help you along the way.

**Comment by madianas** [comment]
+1

**Comment by matthewdickinson** [comment]
@bajtos I would be willing to take a stab at implementing this. Is there an existing connector that implements this that I should review as an example, or would this be the first connector to do this?

**Comment by bajtos** [comment]
> > See #16 automigate and autoupdate currently don't create foreign keys, and it would be nice to have for referential integrity.

> I would be willing to take a stab at implementing this. Is there an existing connector that implements this that I should review as an example, or would this be the first connector to do this?

That's great! I don't know enough about the connectors myself. @raymondfeng @superkhau could you please help @matthewdickinson to get started on this task?

**Comment by superkhau** [comment]
@matthewdickinson It would be the first connector that has this feature. Please create a PR and we can work with you along the way as @bajtos said while you implement this feature. I suggest creating a PR for the memory connector in Juggler and submitting separate PRs for each other connector as we move along. Please link your PR to this issue too so everyone can see the progress being made (or I will link it for you if you ping me on the PR itself).

**Comment by matthewdickinson** [comment]
@superkhau Just so that I'm completely clear: are you saying I should start by implementing this feature in the Memory connector? There's no way that I could actually build out foreign keys using that connector is there? Are you just suggesting that I add a stub to that connector's automigrate function?

**Comment by superkhau** [comment]
@matthewdickinson The change is going to require you to modify various parts of Juggler + connectors in general. What I meant was start with a test that creates a few models with relations and modify the automigrate/autoupdate functions (or related functions) to build out the foreign keys. Then run your test against your changes to verify the output and submit all this as a PR. ;)

**Comment by loay** [comment]
Issue is fixed ...
If you are still running into the same problem, please leave a comment .. Thanks

**Comment by buokae** [comment]
I followed exactly the steps mentioned here: https://loopback.io/doc/en/lb3/MySQL-connector.html#auto-migrateauto-update-models-with-foreign-keys

The Book and Author tables are nicely created, but the foreign key is not. So I currently still run into this problem.
