### ISSUE TITLE
loopback with orientdb

### ISSUE THREAD

**Issue by smart548** [strongloop/loopback-connector-mysql#141]
Hi!
I know the existence of this connector: https://github.com/mattaylor/loopback-connector-orientdb

Still, it is written that its behaviour looks like this connector(mysql). Do you have suggestions on how to proceed? I've already tried to follow the step by step guide on the StrongLoop website, but I find myself trapped into an issue reguarding the loopback-connector-juggler when running the app (with the node . command). For example I got that error:

C:\loopback-gettin-started\node_modules\loopback-datasource-juggler\lib\datasour
ce.js:1706
throw new Error('The connector has not been initialized.');
^

Error: The connector has not been initialized.

Thanks for all the help you'll be able to give me.

**Comment by loay** [comment]
Hi @smart548 
Thanks for reporting the issue. 
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

There might be a discussion about orientdb in the groups and you can get some help from the community there. 
If you are still having an issue with it, please give me a link to your repository on github so we can have a look and help out. 
Thanks
