### ISSUE TITLE
executeSQL() - how to use it?

### ISSUE THREAD

**Issue by richardaum** [strongloop/loopback-connector-mysql#144]
How to use the function executeSQL(.) to run raw queries? Example provided here is not enough: https://docs.strongloop.com/display/public/LB/Executing+native+SQL, because when I try to call the function a few exception are thrown:

1. When calling executeSQL(query, params, options, cb) throws this.settings.database is not defined.
2. When call executeSQL.call(MyModel, query, params, options, cb) throws this.client is not defined.

How to proceed?

**Comment by superkhau** [comment]
See https://github.com/strongloop/loopback-datasource-juggler/issues/176#issuecomment-49191676

tldr;
You should still configure the datasource in juggler and execute from there.
