### ISSUE TITLE
Can't set a model prop as Unique in the db

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback-connector-mysql#147]
Hi, I have connected to my models a mySql DB.
I want to flag a property as Unique, how can I write my model?
I already have a Primary Key in my model, I just want this prop to be Unique.

This is what I found in the docs : https://docs.strongloop.com/display/public/LB/Validating+model+data)

```
module.exports = function(user) {
 user.validatesUniquenessOf('email', {message: 'email is not unique'});
})
```

but this is a programmatic validation, this will not generate a "user" table with a "unique" "email" column in the DB.

I also found this in the docs : (https://docs.strongloop.com/display/public/LB/MySQL+connector)

```
"locationId":{
    "type":"String",
    "required":true,
    "length":20,
    "mysql":
    {
        "columnName":"LOCATION_ID",
        "dataType":"VARCHAR2",
        "dataLength":20,
        "nullable":"N"
    }
}
```

I can't see a field like "Unique": true\false... What am I missing?

**Comment by jannyHou** [comment]
@giowe from function [`buildColumnDefinition`](https://github.com/strongloop/loopback-connector-mysql/blob/37bb679f6e5527651d98bf1e9cdb25693ef799f9/lib/migration.js#L476) I don't see we accept an option to specify a property as `unique`.
Label it as a feature.
And if you are ok to fork this repo to get unique work, making change in that function above is a choice.

**Comment by giowe** [comment]
oook :+1:

**Comment by kjdelisle** [comment]
You can define a unique index for the column.
```
// Model definition
{
  "email": {
    "type": "String",
    "index": {
      "unique": true
    }
  },
  // etc.
}
```

Closing this ticket. Terribly sorry for the late reply. If you're still interested, and this doesn't help, please let us know.
