### ISSUE TITLE
Multiple Foreign Keys in loopback model relation??

### ISSUE THREAD

**Issue by chojowliu** [strongloop/loopback-connector-mysql#150]
n the loopback model relations section, you can specificity a foreignKey to be referenced in the other model. As far as I know, It will only take one field, but what about I have a composite primary key and want to be referenced in the other model?

Can I do something like?

`"foreignKey":["id1","id2"]`

**Comment by jmls** [comment]
did you ever get an answer on this ? I have the same need ;)

**Comment by WardBeullens** [comment]
+1

**Comment by palafoxisc** [comment]
I need to know too how can I achieve that.

**Comment by archenroot** [comment]
+1
Same here, I think it is quite common in business key driven databases, still stuck on this.

**Comment by kamilml** [comment]
I have the same problem... I need two ForeignKey for the same model in the same relation :(
