### ISSUE TITLE
Foreign Key constraints are not honoured..

### ISSUE THREAD

**Issue by hussainak** [strongloop/loopback-connector-mysql#158]
This connector does not seem to honour foreign key constraints when the model is persisted to the database. This can potentially result in referential integrity issues. Is there a plan to include this feature in future releases?

Regards

**Comment by shaheero** [comment]
Foreign key constraints were referenced fine in my case with loopback discovery when `associations: true`. An example script can be found here (it has an wrong extra closed bracket at `_.each(models` that needs to be removed though.

[http://stackoverflow.com/questions/34630182/strongloop-discovery-model-still-empty]

**Comment by jannyHou** [comment]
@hussainak Do you still run into same issue? 
Can you fork https://github.com/strongloop/loopback-sandbox and replace with your use case? Thanks.

**Comment by kjdelisle** [comment]
Closing as inactive.
