### ISSUE TITLE
GROUP BY is not supported

### ISSUE THREAD

**Issue by jdschreck** [strongloop/loopback-connector-mysql#159]
It seems like there is no way to provide a GROUP BY specification to the SQL query.  Seems like this could be implemented very similarly to ORDER BY.  Is there a technical reason that this has not been implemented?  Are you expecting GROUP BY type operations to be performed some other way?

**Comment by mclark-newvistas** [comment]
See also #44 for a previous attempt and some relevant discussion.

**Comment by gbhipolitoglyph** [comment]
group by pls?
