### ISSUE TITLE
How to access information_schema of any table of postgres using loopback

### ISSUE THREAD

**Issue by abdulqudoos** [strongloop/loopback-connector-mysql#163]
Hi,
I want to know to column_name and data_type of tables in my angular app. In loopback how can I run sql native query. I am using remote method for this but it gives error {"name":"error","status":500,"message":"operator does not exist: information_schema.sql_identifier =?"......,
is loopback support this? or is there any other way to do this?
Thanks

**Comment by ssh24** [comment]
@abdulqudoos You can use to discovery properties to discover `column_name` and `data_type` properties of a given table.

Example script:
```
'use strict';
var loopback = require('loopback');
var ds = loopback.createDataSource('mysql', {
  'host': 'localhost',
  'port': 3306,
  'database': 'information_schema',
  'username': '<my_user>',
  'password': '<my_pass>',
});

// Create a model definition by discovering the given table
ds.discoverSchema('VIEWS', function(err, table) {
  if (err) throw err;
  console.log(JSON.stringify(table));
});
```

**Comment by kjdelisle** [comment]
Answered, closing.
