### ISSUE TITLE
Setting mysql datatype option in Model is not reflected in database.

### ISSUE THREAD

**Issue by TheRossman** [strongloop/loopback-connector-mysql#165]
Hi,

I have a model definition file and one of the fields is defined as follows:
`    "rating": {
      "type": "number",
      "mysql": {
        "dataType": "float"
      }
    },`

Unfortunately, when I run the auto update script to update the database to match our models, this dataType is not respected and the rating field is always set to INT(11).
 
I looked into the migrate.js file that is part of this repo and it doesn't look like it respects those custom mysql datatype properties?  I have fixed this locally in our own version by adding some JS to check for the mysql object on each model field and to use it, if it's supplied.

I was wondering if I am doing something wrong or if perhaps I could contribute my fix for this to the repo?

Thank you,
mark

**Comment by TheRossman** [comment]
Sorry I didn't read the documentation well enough, I mistakenly thought that you set the datatype in the mysql block but it is set outside for floats.  cheers!

**Comment by bbito** [comment]
@TheRossman can you share the solution? I find the documentation unclear.
Did you end up with
```
"rating": { 
  "type": "number", 
  "dataType": "float",
  "mysql": { 
    "dataType": "float" 
  }
 },
```
I've gone over the doc page: [https://docs.strongloop.com/display/APIC/MySQL+connector#MySQLconnector-Floating-pointtypes](url)
I would find the solution to your use case helpful if you don't mind.

**Comment by TheRossman** [comment]
For floats you don't need the mysql block, so just like:

```
"rating": { 
  "type": "number", 
  "dataType": "float"
}
```

**Comment by bbito** [comment]
Thanks, so in that case you would only include the mysql block if you were going to specify a different column name, or make it nullable, etc...

**Comment by TheRossman** [comment]
or set to varchar type, yeah  :)  thats why i was confused, we used the mysql block to set varchar types before and had no issue!

cheers
