### ISSUE TITLE
Specify timeout value

### ISSUE THREAD

**Issue by angus-ics** [strongloop/loopback-connector-mysql#167]
I'm running on some pretty crappy hardware, so the current default timeout of 10,000 milliseconds isn't really long enough. Could allow passing in a timeout parameter over to the mysql NPM package? I took a look at the code and wouldn't mind creating a PR. 

Don't want to do this if it's already possible though.

**Comment by superkhau** [comment]
I don't believe its possible in the connector ATM (@raymondfeng please confirm). Please submit a PR in the meantime and we can move forward there. In addition, please connect that PR to this issue.

**Comment by bbito** [comment]
@angus-ics , @superkhau  - I think we confirmed that passing a `connectTimeout` parameter to mysqljs/mysql is possible here: https://github.com/strongloop/loopback-connector-mysql/issues/210#issuecomment-256933458
Perhaps this can be closed?

**Comment by superkhau** [comment]
@bbito Thanks for the confirmation, yes I believe we can close this. :clap:

@angus-ics See #210 and ping if you are still running into issues.
