### ISSUE TITLE
[Documentation] connectionLimit parameter is not in documentation

### ISSUE THREAD

**Issue by jaime-franco** [strongloop/loopback-connector-mysql#171]
I was looking the name of the parameter for limit the connections in the documentation from loopback mysql connector but didn't find the `connectionLimit` parameter in the [documentation](https://docs.strongloop.com/display/public/LB/MySQL+connector), i had to search in the issues of the repo to find out what is the name of the parameter.

If the parameter could be add to the documentation that will be great :)

Thanks

**Comment by salkz** [comment]
I agree. Had to `CTRL + F 10` from the source code to see where the connection pool is set and found that you can use `connectionLimit` in `datasources.json` .

**Comment by crandmck** [comment]
Notice the link (below the table) to https://github.com/mysqljs/mysql#connection-options where this property (and others) is documented.  Anyway, I went ahead and added `connectionLimit` and a couple of the other properties to the table in http://loopback.io/doc/en/lb2/MySQL-connector.html.

This should address the issue... LMK if not; thanks.
