### ISSUE TITLE
autoupdate and automigrate functions don't create the linking table in mysql DB

### ISSUE THREAD

**Issue by yotamsha** [strongloop/loopback-connector-mysql#172]
I've set up new relation using the `slc loopback:relation` command, using the `HasAndBelongsToMany` property.
According to [this](https://docs.strongloop.com/display/public/LB/HasAndBelongsToMany+relations) , a new linking table should be created when I run `autoupdate`or `automigrate`, but no such table seems to be created in the DB.

**Comment by tommedema** [comment]
Surprisingly this doesn't seem to be a feature of loopback, making automigration not very useful since you'll need to install another method for migrations. Any recommendations on a proper migration tool for a database like MySQL?

**Comment by lintiwen** [comment]
We had the same issue and we end up having to manually specify a connecting Model like:
```
ds.automigrate('AssemblyPart', (err) => { });
```

Any plan on what to do next for this issue?
