### ISSUE TITLE
Documentation states there is an `Enum` type in loopback

### ISSUE THREAD

**Issue by tkrugg** [strongloop/loopback-connector-mysql#173]
There is no mention of this Enum type anywhere in [loopback types docs](https://docs.strongloop.com/display/public/LB/LoopBack+types), so it looks like a mistake. 

![image](https://cloud.githubusercontent.com/assets/2982512/16703606/4da3b008-456f-11e6-88a8-0976eedcb165.png)

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
I believe this refers to a "custom" Enum type described in https://docs.strongloop.com/display/APIC/MySQL+connector#MySQLconnector-Enum.  I added a link in the table to that section later in the page.  @superkhau Can you please confirm that's correct.

**Comment by tkrugg** [comment]
I think too, but the way it was put under the column LoopBack type is confusing imho.

**Comment by crandmck** [comment]
OK, I added a link to that section in the table.  I hope this helps to avoid any confusion.  I'll go ahead and close this--thanks for letting us know!
