### ISSUE TITLE
How I can get date from timestamp without timezone?

### ISSUE THREAD

**Issue by A11oW** [strongloop/loopback-connector-mysql#174]
I use PostgreSQL and columns with simple timestamp. loopback return data with time zone.
For example in base data look like this: `2016-01-01 00:00:00.000000`, loopback return `start: "2015-12-31T21:00:00.000Z",`

Model look like this:
```
    "start": {
      "type": "Date",
      "required": true,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "start",
        "dataType": "date",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      },
      "_selectable": false
    },
```

Loopback return data with time zone and dates different. How I can get data without timezone?

**Comment by superkhau** [comment]
See https://docs.strongloop.com/display/public/LB/Operation+hooks. Use a hook and modify the returned timezone accordingly.

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
