### ISSUE TITLE
Missing methods buildReplaceFields and buildFields

### ISSUE THREAD

**Issue by IDispose** [strongloop/loopback-connector-mysql#177]
This is from mysql.js

```
/**
 * Replace if the model instance exists with the same id or create a new instance
 *
 * @param {String} model The model name
 * @param {Object} data The model instance data
 * @param {Object} options The options
 * @param {Function} [cb] The callback function
 */
MySQL.prototype.replaceOrCreate = function(model, data, options, cb) {
  var fields = this.buildReplaceFields(model, data);
  this._modifyOrCreate(model, data, options, fields, cb);
};
```

The buildReplaceFields methods seems to be missing. While invoking the replaceOrCreate method on my loopback.io API, the get an error 

"this.buildReplaceFields is not a function"

Where is the method defined?

**Comment by jannyHou** [comment]
@IDispose It's defined in loopback-connector:
https://github.com/strongloop/loopback-connector/blob/c6a68ec5d8c94f293f04eab6986e69113797ebc3/lib/sql.js#L975

I tried replaceOrCreate with mysql on my end it works fine, if you still see the error, please fork https://github.com/strongloop/loopback-sandbox and replace with your code. Thanks.

**Comment by ssh24** [comment]
Closing this as it is not an issue anymore. Feel free to reopen if needed.
