### ISSUE TITLE
connect ETIMEOUT PoolConnection.Connection._handleConnectTimeout v 2.3.0

### ISSUE THREAD

**Issue by Amatarasu** [strongloop/loopback-connector-mysql#180]
an issue occured when i was trying to do ssl server with package.json file containing version 2.3.0. Had to revert back to version 2.2.1 and it did not show the error message anymore.
![serverconnectionerror](https://cloud.githubusercontent.com/assets/10101217/17297680/52701e2c-57cc-11e6-8bad-1fa647133491.PNG)

**Comment by raymondfeng** [comment]
Can you check if `npm install` pull in the same version of `mysql` driver or not?

**Comment by probil** [comment]
It's related to the #210

**Comment by jannyHou** [comment]
Copied from #210 seems like this is the final solution:

> It seems like no issue anymore with:
    ```
     {
      "mySQL":{
        //...
        "connectTimeout": 20000,
        "acquireTimeout": 20000
    } 
   ```

I am closing this issue as a dup. If related errors happen again let's discuss in issue #210 since more people are involved there.
