### ISSUE TITLE
hasOne relation is built wrong

### ISSUE THREAD

**Issue by tommedema** [strongloop/loopback-connector-mysql#181]
I have two models: `Review` and `Attempt`. Each `Attempt` has one `Review`.

Therefore I run the following commands:

```
Toms-MacBook-Pro:brudy-api tommedema$ slc loopback:relation
? Select the model to create the relationship from: Attempt
? Relation type: has one
? Choose a model to create a relationship with: Review
? Enter the property name for the relation: reviews
? Optionally enter a custom foreign key: 
```

The result is the following `Attempt.json` relations:

    "relations": {
      "reviews": {
        "type": "hasOne",
        "model": "Review",
        "foreignKey": ""
      }
    },

This makes sense. Attempt hasOne review.

However, when I then run `automigrate` the result is that the `Review` table has a column `attemptId`, indicating that each `Review` has one `Attempt`. This is obviously wrong and inversed from what it should be.

Also, other relations (hasMany etc.) are not created at all.

**Comment by bbito** [comment]
In your shoes I would start with a `belongsTo` relation for the model you want the FK added to. From your post it seems you don't want the FK added to `Review`, so:
```
? Select the model to create the relationship from: Attempt
? Relation type: belongs to
? Choose a model to create a relationship with: Review
? Enter the property name for the relation: reviews
? Optionally enter a custom foreign key: 
```
That should add the FK `reviewId` to `Attempt` and give you the API url:
`GET /Attempts/{id}/review`

If you want to expose the corresponding API for the `Review` model, add a `hasOne` or `hasMany` relation to the `Review` model:
```
? Select the model to create the relationship from: Review
? Relation type: has one
? Choose a model to create a relationship with: Attempt
? Enter the property name for the relation: attempts
? Optionally enter a custom foreign key: 
```
That should not add any new columns, but should provide new `Review` API urls:
```
GET /Reviews/{id}/attempts (Fetches hasOne relation attempts.)
PUT /Reviews/{id}/attempts (Update attempts of this model.)
POST /Reviews/{id}/attempts (Creates a new instance in attempts of this model.)
```

See also:
https://groups.google.com/forum/#!topic/loopbackjs/fB06fS6KOEs

**Comment by tommedema** [comment]
I could perhaps fix it by adding the inverse relationship (belongsTo), but that still leaves `hasOne` bugged, right?

The author in the thread you linked describes it appropriately:


```
 For some reason an "A hasOne B" creates B.AId. There would appear to be two issues here:

1. Having the relation in B means you can have many Bs in A, which breaks the relation. The FK should be BId in A, thereby enforcing the singularity of the relation.
...
```

This is exactly the issue that I am experiencing too. If I say that A has one B, then A has 1 be, and not more. With the current setup, A can have multiple Bs and B can only have a single A. This is inversed of the desired behavior.

**Comment by bbito** [comment]
I won't comment on the validity of the semantics, but it seems to me that Loopback is using the terms in the same manner as other popular ORMs:
Sequelize: 
> HasOne and BelongsTo insert the association key in different models from each other. HasOne inserts the association key in target model whereas BelongsTo inserts the association key in the source model.

http://docs.sequelizejs.com/en/latest/docs/associations/

Eloquent:
https://laravel.com/docs/5.1/eloquent-relationships#one-to-one

**Comment by bbito** [comment]
@tommedema Although Loopback (and the other ORMs) is not generating a database schema that enforces a 1:1 relationship, the framework itself will not allow you to assign more than one `Attempt` for a given `Review`.
If I try to `POST` a new `Attempt` to a `Review` that already has one asigned, the operation fails with a 500:
```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "HasOne relation cannot create more than one instance of Attempt",
    "stack": "Error: HasOne relation cannot create more than one instance of Attempt\n    at C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\relation-definition.js:1720:18\n    at C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:915:13\n    at doNotify (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:98:49)\n    at doNotify (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:98:49)\n    at doNotify (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:98:49)\n    at doNotify (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:98:49)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:121:5)\n    at Function.ObserverMixin.notifyObserversOf (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:96:8)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:119:15)\n    at Function.ObserverMixin.notifyObserversOf (C:\\src\\lb\\issue-181\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:96:8)"
  }
}
```

**Comment by tommedema** [comment]
Thanks. I'm not sure why the database would be setup like so (I don't think it is the most senseful implementation), but I guess this has already been agreed upon. Closing.

**Comment by andrewferk** [comment]
> This is obviously wrong and inversed from what it should be.

No, it is not wrong, this is how foreign keys work. 
`loopback-connector-mysql` is doing it correctly. The foreign key should be on the target table. In your example, `Attempt` has one `Review` (implied `Review` belongs to `Attempt`), the `Review` table should have a foreign key to the primary key of the `Attempt` table.

```sql
CREATE TABLE `attempts` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
);

CREATE TABLE `reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `attempt_id` int NOT NULL,
  UNIQUE KEY `attempt_id_unique` (`attempt_id`),
  CONSTRAINT `fk_attempt_id` FOREIGN KEY (`attempt_id`) REFERENCES `attempts` (`id`)
);
```

**Comment by tommedema** [comment]
@andrewferk I see. Thanks a lot for elaborating, much appreciated
