### ISSUE TITLE
DATETIME: fractional seconds part

### ISSUE THREAD

**Issue by NTag** [strongloop/loopback-connector-mysql#183]
Hello,

I have a model with a date field. In MySQL the type of the field is `DATETIME(3)` which means that it will store milliseconds (http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html).
However, when I try to save a date which has milliseconds, in the database they disappear and I always get 0 milliseconds.

Do you support fractional seconds part?

Thank you very much,
Basile

**Comment by jannyHou** [comment]
Didn't figure out a way to specify fractional seconds.
This is what I tried on local but doesn't work:
```js
  // Model json file
  "name": "Mytest",
  "properties": {
    "mydate": {
      "type": "date"
    },
    "fraction": {
      "type": "date"
    },
    "fraction4": {
      "type": "date",
      "mysql":
      {
        "columnName":"fraction4",
        "dataType":"DATETIME(4)"
      }
    }
  },
```
Data stored in mysql:
```js
//In explorer the instance is created as {"fraction4": "2016-12-06T19:42:38.5684"' }
// milliseconds disappeared and saved as '.0000'
fraction4:  '2016-12-06 19:42:38.0000'

```

**Comment by nqd** [comment]
+1 to support ms supported

**Comment by joostdebruijn** [comment]
I purposed a pull request for this. I'm awaiting feedback of the maintainers now.

**Comment by jannyHou** [comment]
I will take a look asap

**Comment by ssh24** [comment]
Should be fixed in https://github.com/strongloop/loopback-connector-mysql/pull/274
