### ISSUE TITLE
Fix support for MySQL 5.7 in test that cause CI to fail

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-mysql#188]
See https://cis-jenkins.swg-devops.com/job/nb/job/loopback-connector-mysql~master/label=nvm%20&&%20dbs,nodeVersion=0.10/65/consoleFull#-207526304206f8fc75-e0b9-479e-b471-e8fe633361ff.

CIS-Jenkins is running MySQL 5.7 which is the result of the above failure. We need to figure out what are the officially supported versions and either:
1. Drop support for version 5.6
2. Modify tests to detect/run based on versions
3. Modify CIS-Jenkins to also use 5.6 (probably not a good solution since we should be encouraging 5.7 these days)

Anyways, whoever is working on this can dig deeper.

**Comment by superkhau** [comment]
cc @rmg 

I'm also voting for number 2 to modify tests to support multiple version.

**Comment by rmg** [comment]
See also: https://github.com/strongloop/loopback-connector-mysql/pull/187#issuecomment-241111013

**Comment by ssh24** [comment]
Closing this issue. All tests cases pass on CI for MySQL in both CIS-jenkins and CI-strongloop. 

CIS uses mysql version 5.7 and CI strongloop uses 5.6. The tests are supported to detect and run on both 5.6 and 5.7.
