### ISSUE TITLE
Extended operators

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-connector-mysql#206]
Is there any effort currently to implement atomic increment/decrement/etc for this connector, just like the [mongodb connector](https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-UsingMongoDBoperatorsinupdateoperations) ?

If not, would you be open to a PR ?

**Comment by superkhau** [comment]
Nothing on the roadmap ATM, please submit a PR and I will try to get it landed for you.

**Comment by Overdrivr** [comment]
Diving into the code, I realize that the base operations (save, update, etc) are mostly implemented in loopback-connector repo, in the [SQLConnector object](https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js), and not in this repo.

I was able to get `$inc` operator to work by modifying slightly [SQLConnector.prototype.update](https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L677) in loopback-connector.

I'm not sure it's the best place for implementing this, but it works. Let me know your feedback if really that sounds like a bad idea. Otherwise, I'll make a PR on loopback-connector repo, referencing this issue.

**Comment by superkhau** [comment]
@Overdrivr The base connector is for shared functionality amongst all connectors. I would say extended MySQL ops are specific to the MySQL domain and should remain with this connector. That is unless you can ensure the $inc operator will work the same across all connectors (we would need tests to verify this of course).

**Comment by Overdrivr** [comment]
Well, for instance, the `$inc` operator just translates in `SET field = field + inc`, so I guess it's fine to have it in the base connector.

Just one more question, where are the tests located for the base CRUD methods ? For instance, where is tested `MySQLConnector.update` so that I can add tests for extended operators alongside ?

**Comment by superkhau** [comment]
@Overdrivr Makes sense, I would be open to it since it seems replicable across all relational DBs (and as you said, we already have it in the mongodb connector). @bajtos @raymondfeng @strongloop/fa-db-connectors Any objections to @Overdrivr's proposal?

**Comment by superkhau** [comment]
>Just one more question, where are the tests located for the base CRUD methods ? For instance, where is tested MySQLConnector.update so that I can add tests for extended operators alongside ?

Take a look at https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js -- these tests are shared amongst all connectors.

**Comment by bajtos** [comment]
> Any objections to @Overdrivr's proposal?

@superkhau The proposal sounds reasonably to me.

**Comment by superkhau** [comment]
> I'm not sure it's the best place for implementing this...

@Overdrivr Take a look at:

- https://github.com/strongloop/loopback-datasource-juggler
- https://github.com/strongloop/loopback-connector
- Any connector you see under the strongloop org: https://github.com/strongloop/?utf8=%E2%9C%93&query=connector

Feel free to ping in the PR you submit if you need some feedback.

**Comment by Overdrivr** [comment]
Just following up, I have made the changes in the [loopback-connector](https://github.com/strongloop/loopback-connector/pull/64) repo.

For now I am testing the PR with tests inside loopback-connector-mysql. However I have the following issue.

> [..] If I move & push [those tests] to loopback-datasource-juggler, they will most likely break tests for non-sql databases that don't implement these operators yet. What do you think should be done ?

Any ideas ?

**Comment by superkhau** [comment]
@Overdrivr We can return an unsupported error message for those connectors for now. The painful part is we'll need to do that for each connector and then merge the juggler PR last.

**Comment by Overdrivr** [comment]
Isn't mentionning in the docs that extended operators are not supported on those connectors enough ?
Maybe the juggler tests can check if the DB is a SQL one, otherwise skip the test. Does this sound ok ?

Otherwise this would give the following list:

- [ ] [DB2](https://github.com/strongloop/loopback-connector-db2)
- [ ] [Informix](https://github.com/strongloop/loopback-connector-informix)
- [ ] [DB2iseries](https://github.com/strongloop/loopback-connector-db2iseries)
- [mqlight ?](https://github.com/strongloop/loopback-connector-mqlight)
- [ ] [DB2Z](https://github.com/strongloop/loopback-connector-db2z)
- [ ] [](https://github.com/strongloop/loopback-connector-cloudant)
- [Swagger ?](https://github.com/strongloop/loopback-connector-swagger)
- [ ] [kv-extreme-scale](https://github.com/strongloop/loopback-connector-kv-extreme-scale)
- [ ] [Redis](https://github.com/strongloop/loopback-connector-redis)
- [ ] [kv-Redis](https://github.com/strongloop/loopback-connector-kv-redis)
- [ ] [Oracle](https://github.com/strongloop/loopback-connector-oracle)

If really that's the way to go I'm ok tackling most of them. Please let me know if I forgot some.

**Comment by superkhau** [comment]
Unfortunately, at this time Juggler does not know what type of DB it is -- this is on the roadmap I believe for the Juggler refactor. Basically your list to update is fine.
