### ISSUE TITLE
Support table configurations like COLLATE when migrate models to mysqlDB

### ISSUE THREAD

**Issue by acrodrig** [strongloop/loopback-connector-mysql#207]
I would like to be able to use a `utf8mb4` character set in the tables that are automatically created by Loopback. I have not been able to find a configuration option that allows me to tell Loopback which character set/collation to use.

Can you help?

**Comment by jannyHou** [comment]
I don't see any code in function [`createTable`](https://github.com/strongloop/loopback-connector-mysql/blob/955f5dc084eea94a43a479d27591e26bb650e3d9/lib/migration.js#L60) adding settings/config to the SQL. 
Label it as a feature here.
And if you don't mind, I changed the title to "Support table configurations like COLLATE when migrate models to mysqlDB"

**Comment by lsocrate** [comment]
I have it implemented here https://github.com/lsocrate/loopback-connector-mysql/tree/collation-support, but I still gotta add tests to it.

**Comment by jannyHou** [comment]
@lsocrate sounds good, thank you for taking look into the feature, have you created a pr for it? I can help review after tests added. And take your time for the tests.
