### ISSUE TITLE
Document mysql for handling booleans

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-connector-mysql#208]
Document https://github.com/strongloop/loopback-connector-mysql/pull/202 after landing.
Should be documented here: http://loopback.io/doc/en/lb2/MySQL-connector.html#type-mappings

**Comment by shaheero** [comment]
It's weird how a Boolean Loopback -> TINYINT(1) MySQL, while the opposite is not the same.
Also, MySQL Char(1) converted to Boolean successfully but always gave true in my project.

**Comment by ssh24** [comment]
The docs have been updated in [here](http://loopback.io/doc/en/lb2/MySQL-connector.html#type-mappings). Closing this issue.
