### ISSUE TITLE
Fix Windows failures on CI

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-mysql#209]
This has been going on way too long, creating this task to get it into planning.
- Each Node version has 50+ errors when running CI on windows.

Estimating at a whole sprint because:
1. Need to set up local windows instance
2. Not sure how long each failure is going to take to fix

Better to timebox this task this.

cc @bajtos

**Comment by superkhau** [comment]
@siddhipai Is working on getting instructions for number 1 and @loay Has been working on number 2 for a a few weeks now. Will revisit at the end of sprint to see how far things get and whether this can be closed.

**Comment by loay** [comment]
@superkhau 

I think this issue could be closed now. 
I am not sure what happened for number one but you can do the following to test locally:

1) download mysql 5.7 and make sure you include the installation on mysql workbench as well. 

2) edit test/init.js 
```
// var config = require('rc')('loopback', {test: {mysql: {}}}).test.mysql;
// console.log(config);
global.getConfig = function(options) {
  var dbConf = {
    host:  'localhost',
    port: 3306,
    database: 'myapp_test',
    username: [root or any local username],
    password: [root password or local username password],
    createDatabase: true,
  };
```
3. run `npm test`

**Comment by superkhau** [comment]
>make sure you include the installation on mysql workbench as well.

Why does workbench matter? I'm not following.

**Comment by loay** [comment]
Sorry I meant `of` workbench, not `on` .. I fixed the typo. When you install mysql 5.7, you need to add workbench so it will be easier to add/remove db, add /remove user ..etc

**Comment by superkhau** [comment]
@loay I assume no setup is needed to run npm test (except maybe create `myapp_test` DB)? Anyways, looks like a usability issue -- that config should take in a dynamic database name via process.env.MYSQL_DB anyways). Hence no need for workbench (I could do it from MySQL CLI anyways).

**Comment by superkhau** [comment]
Prerequisite:

- Windows VM
- Git on windows

- [ ] Install MySQL 5.7
- [ ] Clone loopback-connector-mysql
- [ ] Run npm and ensure it passes (fix if trivial, create new issue with estimate for non-trivial)

**Comment by ssh24** [comment]
@superkhau @loay CI runs properly on windows. Can this issue be closed?

**Comment by ssh24** [comment]
Closing this as CI on windows is working.
