### ISSUE TITLE
Emojis displayed as question marks ? in the JSON

### ISSUE THREAD

**Issue by shaheero** [strongloop/loopback-connector-mysql#213]
I have a utf8mb4 MySQL db and tables, and the emojis are saved and viewed fine there. But they are shown as '?' in the returned JSON. Any solution?

**Comment by shaheero** [comment]
In node_modules/mysql/lib/ConnectionConfig.js line 56, changed:
`: options.charsetNumber||Charsets.UTF8_GENERAL_CI;`
to
`: options.charsetNumber||Charsets.UTF8MB4_GENERAL_CI;`

Now emojis are displayed correctly.

**Comment by iamfrntdv** [comment]
Is there more practical way to do that? trough config?

**Comment by shaheero** [comment]
Haven't found something right away. But would be better of course. Anyone?

**Comment by iamfrntdv** [comment]
I have found the good way. Just add this into datasources.json to you mysql connection config
```
"charset": "utf8mb4",
"collation": "utf8mb4_general_ci"
```
and it should work!

**Comment by shaheero** [comment]
Didn't work for me..

**Comment by cheese10yun** [comment]
@iamfrntdv 

thank you `datasources.json` change

**Comment by shriIT** [comment]
> In node_modules/mysql/lib/ConnectionConfig.js line 56, changed:
> `: options.charsetNumber||Charsets.UTF8_GENERAL_CI;`
> to
> `: options.charsetNumber||Charsets.UTF8MB4_GENERAL_CI;`
> 
> Now emojis are displayed correctly.

HOW CAN WE SET THIS CHARSET FROM OTHER CONFIG AS NODEMUDULES CAN NOT BE UPLOADED ON SERVER

**Comment by wweevv-johndpope** [comment]
the readme needs "charset": "utf8mb4" added to it.
