### ISSUE TITLE
JSON parser issue

### ISSUE THREAD

**Issue by chinuy** [strongloop/loopback-connector-mysql#217]
at https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L435
No try/catch block in JSON.parse(val). 

I wonder is there any reason not to do so? I got an issue that my db data is corrupt and therefore, the parse will raise exception and crash system every time. I would more like the return is `null` if the JSON.parse() function fail so that I still have chance to just overwrite data.

**Comment by superkhau** [comment]
No reason, probably a oversight -- would you like to submit a PR?

**Comment by chinuy** [comment]
#218 PR created.

**Comment by dhmlau** [comment]
PR #218 is closed with the last comment on Dec 8, 2016: 
`@chinuy Let's close this PR as rejected and you can submit a new PR with the suggested fixed. Feel free to ping @bajtos or me directly when you need another review.`

@chinuy , would you like to submit another PR with the suggestion on #218?  Thanks.

**Comment by chinuy** [comment]
Not in this repo. It would be [loopback-connector](https://github.com/strongloop/loopback-connector). Per discussion on #218, I was stuck in how to handle [`filter.include`](https://github.com/strongloop/loopback-connector-mysql/pull/218#issuecomment-265880248).
