### ISSUE TITLE
Clean up platform test skips

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-mysql#234]
See https://github.com/strongloop/loopback-workspace/pull/408#issuecomment-273726644

cc @bajtos

**Comment by kjdelisle** [comment]
The remaining test skips are from the inherited loopback-datasource-juggler, or are tests that are not supported by current connector functionality.

I've merged a PR against juggler to automatically indicate which tests are unsupported by a connector, which will mark the test-group or individual tests with the `[UNSUPPORTED]` prefix. See https://github.com/strongloop/loopback-datasource-juggler/pull/1398 for details.
