### ISSUE TITLE
nested include not working perfectly

### ISSUE THREAD

**Issue by inggil2407** [strongloop/loopback-connector-mysql#245]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
```
modelOne.find({
  include:[{
  relation:'modelTwo',
  scope:{
    include:[{
     relation:'modelthree',
     scope:{
      limit:1 
     }
    }]
   }
  }]
})
```

only one modelOne.modelTwo with one modelThree
not every modelOne.modelTwo with one modelThree

**Comment by ssh24** [comment]
@inggil2407 What is the exact issue here? Please fill out the above form questions to specify what the problem is, what your expected result versus actual result and specify any additional information.

**Comment by ssh24** [comment]
Closing this issue due to lack of inactivity.
