### ISSUE TITLE
column names are not escaped when creating indexes

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-connector-mysql#259]
### Description/Steps to reproduce
  - Make a model with a property named 'from' (e.g. in a Message-Model)
  - Add an index for the property in the JSON definition file
  - run autoupdate on the datasource

Mysql errors with a PARSE_ERROR

### Expected result
```
CREATE TABLE `Message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `conversation` VARCHAR(512) NULL,
  `text` VARCHAR(512) NOT NULL,
  `created` DATETIME NOT NULL,
  `from` INT(11) NULL,
  `lastUpdated` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL,
   INDEX  `from_index` (`from`),
   INDEX  `conversation_index` (conversation)
)
```
### Actual result which causes PARSE_ERROR by not escaping `from`
```
CREATE TABLE `Message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `conversation` VARCHAR(512) NULL,
  `text` VARCHAR(512) NOT NULL,
  `created` DATETIME NOT NULL,
  `from` INT(11) NULL,
  `lastUpdated` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL,
   INDEX  `from_index` (from),
   INDEX  `conversation_index` (conversation)
)
```

**Comment by ssh24** [comment]
Seems like a bug to me. Here is a [list](https://dev.mysql.com/doc/refman/5.7/en/keywords.html) of reserved keywords in MYSQL and `from` is one of them.

@ernie58 Are you willing to submit a patch to fix this?

**Comment by ssh24** [comment]
Closing this ticket. Issue should be fixed on the next available mysql connector release.
