### ISSUE TITLE
GeoPoint stored as POINT(lat, lon) when it should be POINT(lon, lat)

### ISSUE THREAD

**Issue by tma-isbx** [strongloop/loopback-connector-mysql#269]
From the code:

```
if (prop.type.name === 'GeoPoint') {
    return new ParameterizedSQL({
      sql: 'Point(?,?)',
      params: [val.lat, val.lng],
    });
  }
```

```
      case 'GeoPoint':
      case 'Point':
        val = {
          lat: val.x,
          lng: val.y,
        };
        break;
```

MySQL expects it to be POINT(X, Y) which would be POINT(lon, lat). Storing them transposed would cause confusion when interacting with SQL queries that interact with the POINT. Functions like ST_X(), ST_Y() would be confusing (at best). If MySQL were to support geography based functions that worked on a spheroid in the future, distance calculations would be incorrect.

`SELECT ST_X( POINT( 3, 2 ) ) AS x` returns 3.

**Comment by ssh24** [comment]
@raymondfeng @bajtos Looks like a bug to me. Any reason why we specify the params as `[val.lat, val.lng]` rather than `[val.lng, val.lat]`? And of course need to change 
```
case 'Point':
        val = {
          lng: val.x,
          lat: val.y,
        };
```

**Comment by bajtos** [comment]
IIRC, the last time I was looking into this issue, there was no generally accepted consensus on how to order lat+lng in an array. 

For example, Google Maps uses `(lat, long)` format - see https://developers.google.com/maps/documentation/javascript/reference#LatLng
```
map.setCenter(new google.maps.LatLng(-34, 151));
```

I believe we have modelled our GeoPoint API using Google's approach. Changing the order of lat/lng now would be a huge breaking change.

I think the right solution is to fix the MySQL connector to correctly load/save the GeoPoint type in the format that's used by MySQL.

cc @raymondfeng

**Comment by b-admike** [comment]
@tma-isbx This should be fixed in the next released version of this connector. Thanks!

**Comment by tma-isbx** [comment]
Sounds good!

Though this isn't a breaking change API-wise. It will be a pretty significant breaking change for users that already use GeoPoint with MySQL and have POINTs in their database.

We will lock our version of the connector and manually upgrade it in sync with a database migration. But I assume this could cause some surprises for other users.

**Comment by bajtos** [comment]
> It will be a pretty significant breaking change for users that already use GeoPoint with MySQL and have POINTs in their database.

I agree. IMO, we should release the change as a semver-major version and provide a migration guide explaining how to upgrade the existing data in the database.

**Comment by b-admike** [comment]
@tma-isbx @bajtos Agreed, my apologies. I have a PR up to revert the changes, and the code will live in a branch for next major release.

**Comment by b-admike** [comment]
@tma-isbx Actually, I've merged the code into our master branch based on our branching strategy described [here](https://github.com/strongloop/loopback-connector-mysql/pull/286#issuecomment-305713309). However, we still need a migration guide, and I could use help in drafting it.

**Comment by b-admike** [comment]
Should be fixed in master. PR #286.
