### ISSUE TITLE
Autoupdate Doesn't Honor MySQL 5.7 "JSON" Data Type

### ISSUE THREAD

**Issue by jcq** [strongloop/loopback-connector-mysql#277]
# Description/Steps to reproduce

Add property with "dataType": "JSON" 

# Expected result

Creates a field with "JSON" type on MySQL 5.7 

# Actual result
Creates field of type "TEXT"

Is this due to backwards compatibility with prior versions of MySQL that don't support JSON? Could we simply query for support and fallback to TEXT if version < 5.7?

Making it more annoying, it will alter columns that already have JSON type set to TEXT if autoupdate is run on their model/table.

**Comment by bbito** [comment]
I'd like MySQL JSON type support as well, but today, neither loopback-connector-mysql nor the underlying mysqljs/mysql driver offer first-class support for MySQL JSON columns.
https://github.com/strongloop/loopback-connector-mysql#type-mappings
https://github.com/mysqljs/mysql#type-casting
Until mysqljs/mysql provides first-class support for JSON, there is a workaround, but it requires passing a custom `typeCast` function through the `connection.query` :
https://github.com/mysqljs/mysql/issues/1267#issuecomment-230739821
The better option would be to make a PR at mysqljs/mysql that brings first-class support for this type:
https://github.com/mysqljs/mysql/issues/1267
I imagine loopback-connector-mysql could quickly bring the feature in once implemented in the driver.

**Comment by kjdelisle** [comment]
@bbito From what I understand, this is a more general issue with the automigrate and autoupdate functions not using the mysql-specific column settings. (#281)

cc @ssh24

**Comment by ssh24** [comment]
Closing this. It should be fix on the upcoming release of MySQL.

PR https://github.com/strongloop/loopback-connector-mysql/pull/283
