### ISSUE TITLE
Add docs on foreign key support for automigrate/autoupdate

### ISSUE THREAD

**Issue by haotangio** [strongloop/loopback-connector-mysql#294]
Current the `automigrate` and `autoupdate` methods do not create foreign keys in the database. Do we have any plan to proceed with it?

**Comment by ssh24** [comment]
@haotangio It does create foreign keys in the database when specified. Look at https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/migration.js#L68

**Comment by haotangio** [comment]
This is my `automigrate.js` script applying to https://github.com/strongloop/loopback-example-relations repo:
```
var path = require('path');

var app = require(path.resolve(__dirname, '../server/server'));
var ds = app.datasources.db;
ds.autoupdate(null, function(err) {
  if (err) throw err;
  console.log('Finished migration');
  ds.disconnect();
});
```

But there is still no foreign key created, do I need to add something to the code?
![upload](https://user-images.githubusercontent.com/8952752/27165557-a45fde2c-51cf-11e7-9edc-484cb0b3ef27.PNG)

**Comment by haotangio** [comment]
After a deep reverse engineering for the source coe, I figured out the way to achieve the purpose:

```
{
  "name": "Book",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "author": {
      "type": "belongsTo",
      "model": "Author",
      "foreignKey": "authorId",
      "primaryKey": "id"
    }
  },
  "acls": [],
  "methods": {},
  "foreignKeys": {
    "authorId": {
      "name": "authorId",
      "foreignKey": "authorId",
      "entityKey": "id",
      "entity": "Author"
    }
  }
}
```

But it's very very strange as why loopback didn't put this information in any documents.
Or is there any document that I missed?

**Comment by ssh24** [comment]
@haotangio Good catch with the docs. I will add a quick PR for the fix.

**Comment by ssh24** [comment]
Docs and example landed on MySQL specific readme and should be accessible in [loopback.io](http://loopback.io/doc/) with the next release of docs.

**Comment by haotangio** [comment]
Thank you.
Btw, is there any `secret options` which are helpful but not documented there? :)

**Comment by ssh24** [comment]
Yup. Look in this [doc](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html) for all the options available globally on each connector module.

**Comment by dionisisZyg** [comment]
I tried the example at the link below (in Discovery and auto-migration section) and still no foreign keys are created.
https://github.com/strongloop/loopback-connector-mysql#auto-migration

![fk](https://user-images.githubusercontent.com/29570517/27329812-aba20702-55bf-11e7-94e0-2797c96d78be.png)

Am i missing something?

![code](https://user-images.githubusercontent.com/29570517/27330068-9f24b442-55c0-11e7-91fa-b7a8e89c93ec.png)

**Comment by ssh24** [comment]
@dionisisZyg Good catch. There was a bug in that example. I have updated the example. Please take a look and try again.

**Comment by dionisisZyg** [comment]
@ssh24 Thanks for your reply. I updated the code but still, the foreign key is missing. I made no changes to the example. 
![workbench](https://user-images.githubusercontent.com/29570517/27379762-40621b78-5685-11e7-8330-50f6c224c74e.png)

![models](https://user-images.githubusercontent.com/29570517/27379771-48fbbe2e-5685-11e7-983a-45f5d872f9d8.png)

![sample-models](https://user-images.githubusercontent.com/29570517/27379779-5036bbe4-5685-11e7-83ac-40f1248dcf2f.png)

**Comment by ssh24** [comment]
It is working for me. Which of version of the connector are you using?

**Comment by dionisisZyg** [comment]
"loopback-connector-mysql": "^2.4.1"

**Comment by ssh24** [comment]
Ah, that is the issue. Foreign key migration is not supported in the older versions. Please upgrade to a latest build by doing `npm i loopback-connector-mysql` and try again.

**Comment by dionisisZyg** [comment]
Thank you, everything now is working as expected!

**Comment by mrnetforge** [comment]
Yes solution by @haotangio works fine. But i have question.. what if my foreign key need to SET NULL on DELETE. Its any solution for this? For now all keys that i created are set to RESTRICT.

**Comment by svershin** [comment]
So after a considerable amount of time spent reading this and related threads, I finally figured out how to get a set of models to auto-migrate/update to a live MySQL database:

1. Make sure to include the `foreignKeys` property in the model definition file (HOT TIP: take care to not have duplicate foreign key names across your models).
2. Drop all tables, otherwise there might be errors when performing auto-migrate, due to existing foreign key constraints.
3. Run auto-migrate. This will create the tables, but WILL NOT create the foreign keys, as some of the tables will not exist when auto-migrate is running.
4. Run auto-update. This will update the tables, inserting the foreign keys as appropriate, since all of the tables are now in place.

This really ought to be clearly documented, since the example skims over the "foreign key constraints" issue, and does not provide a real-world solution (i.e. when you already have a bunch of models with multiple relations, which do not easily lend themselves to being ordered in a way to make auto-migrate put in the foreign keys right away).

**Comment by mrnetforge** [comment]
I have pretty good solution that i use for some time, you dont need to drop all tables.

Just use auto-update every time you want to update foreignKeys, but before that remove all foreignKeys from model definition run auto-update, then add new foreignKeys definition and run auto-update.

When run auto-update you need to specify which model you want to update

**Comment by svershin** [comment]
It's easier to drop the tables when you are getting it set-up for the first time. But I suppose deleting the foreign keys will work just the same.

BTW, Loopback's built-in objects (AccessToken, ACL, Role, and RoleMapping) still don't have their foreign keys inserted, since they do not have the `foreignKeys` property in their model definition files. Yes, I suppose one could manually insert the foreign keys, and since those will not be changing, it's not as big of a deal.

**Comment by zaiddabaeen** [comment]
To provide a full solution to this:

- Remove `loopback-connector-mysql` from your package.json.
- Install it again: `npm i loopback-connector-mysql --save`. At the time of writing I got `^5.2.0`
- Have your model as such:

```
{
  "name": "Project",
...
  "relations": {
    "account": {
      "type": "belongsTo",
      "model": "Account",
      "foreignKey": "accountId",
      "primaryKey": "id"
    }
  },
...
  "foreignKeys": {
    "accountId": {
      "name": "accountId",
      "foreignKey": "accountId",
      "entityKey": "id",
      "entity": "Account"
    }
  }
}
```

- Delete your tables from the database.
- Automigrate your models: `app.dataSources.db.automigrate(model)`
- Autoupdate your models: `app.dataSources.db.autoupdate(model)`

Now it finally works.

**Comment by AhmedMasoodSiddiqui** [comment]
autoupdate and automigrate work perfectly the first time when foreign keys are involved, but as soon as the application is restarted i get the following error. Kindly inform if i am doing something wrong?
![error](https://user-images.githubusercontent.com/33754385/37287514-c99fa2e0-2626-11e8-969e-ebc18c378b25.PNG)

**Comment by toychicken** [comment]
We have a production DB that we need to update without losing the data - so, can't do the autoMigrate step first... any clues on how to auto-update our DB, which has FKs?

**Comment by RafaelGomides** [comment]
I made [this](https://github.com/strongloop/loopback-connector-mysql/issues/294#issuecomment-310073937) and [this](https://github.com/strongloop/loopback-connector-mysql/issues/294#issuecomment-308643731). Only setting in my `package.json` the `"loopback-connector-mysql": "5.3.0"`.
And now it's working perfectly.

**Comment by tanatosan** [comment]
I have upgraded my "loopback-connector-mysql": "5.3.0". It works perfectly with one foreign key being added/removed with autoupdate. However, as soon as I add another foreign key, the autoupdate seems to throw exception. This also occurs the same when I add another foreign key to another model definition.

**Comment by gijo-varghese** [comment]
any update for postgres?

**Comment by codepushr** [comment]
Still missing for postgres...

**Comment by ishan123456789** [comment]
Any update on how to do this in `LB4` I'm just starting so it'll be great if you can guide me with LB4

**Comment by gijo-varghese** [comment]
Yes, this is what I dislike in LB. Is it fixed in LB4?

**Comment by zwurv** [comment]
@ishan123456789 and @gijo-varghese - I've just figured out how to do this in LB4, it certainly wasn't easy.

My example is made up of a customer who can have one order (ya, I know, not real but it works and is an ok example).

1. You need to have postgresql running.
2. You need to have at least postgresql datasource configured, likely best to ensure this is working with a simple model.

3. I'm using the following versions straight from my package.json (it's likely best to start a new app using lb4 cli):
  - "loopback-connector-postgresql": "^3.6.0",
  - "@loopback/repository": "^1.1.5"

4. I've added the following scripts to the package.json file:
    "migrate": "npm run build && node ./dist/migrate",
    "migrate:rebuild": "npm run build && node ./dist/migrate --rebuild",

4b. ensure you name your datasource mainDb or rename it in the sample repositories below

5. Newer versions seem to have a migrate.ts file generated for you, please ensure you have this at src/migrate.ts.

6. Add this model, src/models/customer.model.ts:
  import {model, property, Entity} from '@loopback/repository';

@model({name: 'customer'})
export class Customer extends Entity {

  @property({
    type: 'number',
    id: true,
    required: true,
    generated: true
  })
  id: number;

  @property({
    postgresql: {
      columnName: 'name'
    },
    type: 'string',
    required: true,
    index: {
      unique: true
    }
  })
  name: string;

  constructor(data?: Partial<Customer>) {
    super(data);
  }
}

7. Add this model, src/models/order.model.ts:
import {model, property, belongsTo, Entity} from '@loopback/repository';

import {Customer} from './customer.model';

@model({name: 'order',
  settings: {
    foreignKeys: {
      "order_customer_id_fk": {
        "name": "order_customer_id_fk",
        "foreignKey": "customerid",
        "entityKey": "id",
        "entity": "customer"
      }
    }
  }})
export class Order extends Entity {

  @property({
    type: 'number',
    id: true,
    required: true,
    generated: true
  })
  id: number;

  @property({
    type: 'string',
    required: true
  })
  item: string;

  @belongsTo(() => Customer, {keyTo: 'pk'})
  customerId: number;

  constructor(data?: Partial<Order>) {
    super(data);
  }

  getId() {
    return this.id;
  }

}

8. Don't try to be fancy by changing names, all of my fk's in postgres are lowercased without underscores, something somewhere attempts to remove the word Id from the end and causes things to explode.

9. Add the src/repositories/customer.repository.ts:
import {DefaultCrudRepository} from '@loopback/repository';
import {Customer} from '../models';
import {MainDbDataSource} from '../datasources';
import {inject} from '@loopback/core';

export class CustomerRepository extends DefaultCrudRepository<Customer, typeof Customer.prototype.id> {
  constructor(@inject('datasources.mainDb') dataSource: MainDbDataSource) {
    super(Customer, dataSource);
  }
}

10. Add the src/repositories/order.repository.ts:
import {DefaultCrudRepository, BelongsToAccessor, repository} from '@loopback/repository';
import {MainDbDataSource} from '../datasources';
import {Getter, inject} from '@loopback/core';
import {Order, Customer} from '../models';
import {CustomerRepository} from './customer.repository';

export class OrderRepository extends DefaultCrudRepository<Order, typeof Order.prototype.id> {

  public readonly customer: BelongsToAccessor<Customer, typeof Customer.prototype.id>;

  constructor(@inject('datasources.mainDb') dataSource: MainDbDataSource,
              @repository.getter('CustomerRepository') customerRepositoryGetter: Getter<CustomerRepository>) {

    super(Order, dataSource);

    this.customer = this.createBelongsToAccessorFor('customer', customerRepositoryGetter);
  }
}


11. Finally, we can now try to run the migration. Run the migration command from the package.json like so: npm run migrate:rebuild.

I noticed that dropping and recreating causes issues sometimes, ie. you get an error like error: cannot drop table 
Run this same command like 5 times and eventually it becomes unstuck, I will likely put a shim for that into my package.json that captures the error and replies on error (stderr...).

I hope this huge example isn't too yucky and bulky. I really wish that I understood what was happening with the LoopBack4 project. Sometimes I feel as though it's stalled and I'll be using this thing that's only half production ready. On the other hand, find a better server side framework for node/typescript?

**Comment by DanielJaramillo94** [comment]
How should I proceed with LB4?
