### ISSUE TITLE
inq querry return blank 

### ISSUE THREAD

**Issue by ssageghi** [strongloop/loopback-connector-mysql#304]
Hi 
I used mongoDb previously then I migrate to mysql 
I filter my request with inq and it's ok in mongoDb but now i always get blank 
this is my filter value in strongloop explorer 

{"where": {"tags"{"inq":["kitchen"]}}}
 do you now where I was wrong?

**Comment by ssh24** [comment]
Looks like your filter is wrong. Should be `{"where": {"tags": {"inq":["kitchen"]}}}` instead.

Can confirm `inq` operation works in mysql.

Here is a sample code snippet:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mysqlDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo',
            age: 12
        }, {
            name: 'Bar',
            age: 24
        }, {
            name: 'Baz',
            age: 22
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            Employee.find({where: {name: {inq: ['Foo', 'Bar']}}}, function(err, result) {
                if (err) throw err;
                console.log('\nFound instance with inq: ' + util.inspect(result));
            });
        })
    });
};
```

**output**
```bash
sakibs-mac:mysql-304 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { name: 'Foo', age: 12, id: 1 },
  { name: 'Bar', age: 24, id: 2 },
  { name: 'Baz', age: 22, id: 3 } ]

Found instance with inq: [ { name: 'Foo', age: 12, id: 1 },
  { name: 'Bar', age: 24, id: 2 } ]
```

Closing this as resolved. Feel free to reopen if needed.

**Comment by ssageghi** [comment]
it's ok to use it in persian language?
I still get blank

**Comment by ssageghi** [comment]
@ssh24 
I still get blank
 {"where": {"tags": {"inq":["kitchen"]}}}

my model properties:
`  "properties": {
    "date": {
      "type": "date",
      "required": true
    },
    "title": {
      "type": "string",
      "required": false
    },
    "tags": {
      "type": [
        "string"
      ]
    }
  },`


and i want to filter model by tags property
I don't have a problem with mongoDb and my query work fine

**Comment by ssh24** [comment]
@ssageghi After some investigation, this is happening because MySQL **does not** support Array types. We store the array input as a serialized string (i.e if you input `['Sam', 'Bob']`, we store in the database as `"['Sam', 'Bob']"`. 

If you want to use the inq filter you have query the whole **stringified** array. In your case, `{"where": {"tags": {"inq":['["kitchen"]']}}}`.

Thank you for this catch. Reopening this issue to add advisory docs on this topic.

**Comment by ssageghi** [comment]
thank you for helping me 
I try your suggestion and explorer give me this error 
`"message": "invalid value for argument 'filter' of type 'object': {\"where\": {\"tags\": {\"inq\":['[\"kitten\"]']}}}. Received type was string. Error: Unexpected token ' in JSON at position 27"`

**Comment by ssh24** [comment]
@ssageghi Try this: 
```
{"where": {"tags": {"inq":["[\"kitchen\"]"]}}}
```

**Comment by ssageghi** [comment]
Now it's giving me blank again 
![capture](https://user-images.githubusercontent.com/24605214/27507041-4a01c18e-58dc-11e7-9041-d273d9a64eb7.PNG)

**Comment by ssageghi** [comment]
this is result when I don't use filter

**Comment by ssageghi** [comment]
If i give the photo just one tag (kitchen) it's working 
but when i gave him 2 tags , it's giving me blank

**Comment by ssh24** [comment]
That is the expected behavior. The `inq` filter checks for the exact string `"["kitchen"]"` and will return the instance that has only `"["kitchen"]"`. If you have another instance with `"["kitchen", "living room"]"`, it will not work. 

This is a short coming in our connector because of the way we handle Array types to insert into mysql which doesn't have an array data type. It has a `json` data type and you can specify arrays using that type. I will create another story to implement that as a feature.

**Comment by ssageghi** [comment]
thanks

what change I have to do to this code to accomplish that
`"properties": { "date": { "type": "date", "required": true }, "title": { "type": "string", "required": false }, "tags": { "type": [ "string" ] } },`
make [string] to json?

**Comment by ssh24** [comment]
At this moment everything of loopback data type **array** will be stored in MySQL as `TEXT` field. So it is not convenient to make CRUD calls on it. I have created a feature request and put it in our backlog. Thank you for your patience. https://github.com/strongloop/loopback-connector-mysql/issues/305
