### ISSUE TITLE
DATA too long 

### ISSUE THREAD

**Issue by ssageghi** [strongloop/loopback-connector-mysql#307]
Hi
I have an editor that store image as base64 format and make long text 
and when I try to store in mysql I get this error
`"500 - {"error":{"name":"Error","status":500,"message":"ER_DATA_TOO_LONG: Data too long for column 'content' at row 1","code":"ER_DATA_TOO_LONG","errno":1406,"sqlState":"22001","index":0,"stack":"Error: ER_DATA_TOO_LONG: Data too long for column 'content' at row 1\n    at Query.Sequence._packetToError ` 

My Model properties look like this 
`  "properties": {
    "img_url": {
      "type": "string"
    },
    "content": {
      "type": "text"
    }
  },`

How can i fix this?

**Comment by loay** [comment]
Hi @ssageghi 
You can use the `dataType/dataLength` in mysql in order to increase the length of the `img_url`. Please have a look at this example:
https://loopback.io/doc/en/lb2/MySQL-connector.html#using-thedatatypefieldcolumn-option-with-mysql

**Comment by ssageghi** [comment]
@loay I changed the properties like this 
`  "properties": {
    "img_url": {
      "type": "string"
    },
    "content": {
      "type": "string",
      "required": true,
      "length": 20,
      "mysql": {
        "dataType": "LONGTEXT",
        "dataLength": 20,
        "nullable": "N"
      }
    }
  },`

and I get this error
`
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(20) NOT NULL,

`
and I should mention that I save editor text combined with base64 image in content column

**Comment by loay** [comment]
@ssageghi 
Would it be possible to provide a sample repo with ur issue so I can debug?
Thanks

**Comment by ssh24** [comment]
@ssageghi You don't need to specify the `dataLength` for a *LONGTEXT* data type.

Just specify the `dataType` itself for types that do not require explicit lengths:
```json
    "content": {
      "type": "string",
      "mysql": {
        "dataType": "LONGTEXT"
      }
    }
```
Closing this issue as resolved. Feel free to reopen if needed.

**Comment by ssageghi** [comment]
@ssh24 I use the way that you mentioned and content column still is varchar(512) and I still get error

**Comment by ssh24** [comment]
@ssageghi What version of the mysql connector are you using?

**Comment by ssageghi** [comment]
V3.0.0

**Comment by ssageghi** [comment]
@ssh24 I update to version 5 and now it's working fine.
thanks for your help :)
