### ISSUE TITLE
store access tokens

### ISSUE THREAD

**Issue by donno13** [strongloop/loopback-connector-mysql#324]
hie everyone, I am making an application using loopback where I have a client model which has a base as in built User model . I am using  mysql database to  store accesstoken when i login from either user or client.is it possible to store the access tokens seperately i.e if I login from user it will store access token in accesstoken table but if i login from client it will store the access tokens into something like myaccesstokenn table in mysql. I made all the tables also on backend as well as models but i am not sure how would i connect this to client.
plzzz help  ,thanks in advance. @rmg @vectart

**Comment by ssh24** [comment]
You could have two models `accesstoken` which will store the access tokens if logged in as an user and `myaccesstoken` if logged in as a client, and upon login (i.e let's say clicking the login button) your front-end UI needs to perform with the scope of those two models to store the access token for that user with an unique id.

**Comment by donno13** [comment]
thanks for your reply ,i did exactly  same as i have two model one is accesstoken for user and another is myaccesstoken for client.but to get login and logout properties i made base  of client as user instead of persistedModel. so no matter from where i login either from client or user it is storing the accesstokens into accesstoken table only.i dont know how to configure that .plzz help

**Comment by donno13** [comment]
I mean how to make my ui that is loopback explorer behave in tht way
