### ISSUE TITLE
Schema ignored in model definition file

### ISSUE THREAD

**Issue by juan-ferrer-toribio** [strongloop/loopback-connector-mysql#344]
When i define a model via JSON file, the "schema" option is ignored by loopback. It always tries to locate the table in the schema defined in the datasource.

models/model-x.json:

```
{
  "name": "ModelX",
  "options": {
    "mysql": {
      "schema": "schema2",
      "table": "table1"
    }
  },
  "properties": {}
}
```

datasources.json:

```
{
  "ds": {
    "name": "mysql",
    "connector": "mysql",
    "database": "schema1",
    "host": "localhost",
    "port": 3306,
    "username": "root",
    "password": ""
  }
}
```

If I try to call the find() method, it throwns an error:

> Table 'schema1.table1' doesn't exists

**Comment by pbalan** [comment]
@juan-ferrer-toribio I stumbled upon this too. I changed the Model.json to something like below and it worked. All you need to do is move the mysql part outside the options. Found a hint in [loopback-connector](https://github.com/strongloop/loopback-connector/blob/fa6f51d1983571e35ac9c4a8827fb8179cac1f27/lib/sql.js#L297-L309).

```json
{
  "name": "DocTemplate",
  "description": "Stores unique template",
  "base": "PersistedModel",
  "indexes": {},
  "plural": "doc-template",
  "mysql": {
    "table": "doc_template"
  },
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "replaceOnPUT": true,
  "properties": {
    "docTypeId": {
      "type": "Number",
      "required": true,
      "length": 11,
      "mysql": {
        "columnName": "doc_type_id",
        "dataType": "INTEGER",
        "dataLength": 11,
        "nullable": false
      }
    }
  },
  "validations": [],
  "relations": {
    "docType": {
      "type": "belongsTo",
      "model": "DocType",
      "property": "docTypeId",
      "options": {
        "validate": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ]
}
```

**Comment by juan-ferrer-toribio** [comment]
First of all, @pbalan, your solution is only valid for table name. I was asking about the schema name.

Anyway, taking a look at the source code... The Loopback MySQL connector is delegating the table rendering to SQLConnector::tableEscaped() (Part of the loopback-connector module), wich is rendering just the table name, without the schema.

Then, there is no solution for this unless I write my own Loopback connector or rewrite the tableEscaped() function of the Loopback MySQL connector which could end in unexpected results.

**Comment by juan-ferrer-toribio** [comment]
Finally I've found a workaround by setting the schema plus table name at options.mysql.table option. I've tested it for a while and it works correctly.

```
{
  "name": "ModelX",
  "options": {
    "mysql": {
      "table": "schema2.table1"
    }
  },
  "properties": {}
}
```

It works because SQLConnector::tableEscaped() delegates to mysql.escapeId() wich supports escaping qualified identifiers. For more info take a look to 'mysql' module readme.
