### ISSUE TITLE
Establishing MySQL connection over SSL

### ISSUE THREAD

**Issue by fahmie78** [strongloop/loopback-connector-mysql#347]
# Description/Steps to reproduce

Feature: Establishing MySQL connection over SSL. It would be nice if there are parameters to enable MySQL over SSL in datasource.json. Loopback:connector:Mongodb already has one.

# Link to reproduction sandbox

n/a

# Expected result
Able to establish MySQL over SSL by configuring parameter in datasource.json with or without supplying cert parameters.

# Additional information
n/a

**Comment by fahmie78** [comment]
Problem solved. 

datasource can accept options "ssl": true, but make sure don't use url parameter.

**Comment by rododavid19** [comment]
How can you specify the ca, key, and cert files? is it in the same Datasource.json? and if so what's the correct syntax? Thanks

**Comment by sebastian-capicua** [comment]
+1 for @rododavid19 comment, I too am looking for a way to use a pem key with my MySQL datasource

**Comment by KalleV** [comment]
For anyone else coming across this issue with a search: support for configuring additional options like SSL certs was added here: https://github.com/loopbackio/loopback-connector-mysql/issues/46.
