### ISSUE TITLE
Loopback Mixed Transaction Bug

### ISSUE THREAD

**Issue by CaseyMichael** [strongloop/loopback-connector-mysql#349]
Should having mixed transactions in loopback have the appropriate isolation?

# Description/Steps to reproduce
### Mysql Setup
1. Install mysql with username `root` and no password
2. Run sql script `server/sql/create-db.sql`

### Application setup
1. Install dependencies `npm install`
2. Start the server `npm start`

### Testing setup
1. `touch timeouts.json` to create an empty file for the post request
2. Run the Apache bench command `ab -p timeouts.json -n50 -c50 localhost:3000/api/TestingTransactions/all-transactional`
3. Verify that nothing was committed to the database table because all the requests should of timed out.
4. Restart node server
5. Run the Apache bench command `ab -p timeouts.json -n50 -c50 localhost:3000/api/TestingTransactions/mixed-transaction`
6. Expect 50 rows with the value 10, and 0 rows with the value 0. However I seem to always get a few records with the value 0.

# Link to reproduction sandbox
https://github.com/CaseyMichael/loopback-transaction-bug 

# Expected result

`ab -p timeouts.json -n50 -c50 localhost:3000/api/TestingTransactions/all-transactional`
I expect no records to be committed with this command and it works correctly.

`ab -p timeouts.json -n50 -c50 localhost:3000/api/TestingTransactions/mixed-transaction`
I expect 50 records with the value 10, and no records with the value 0 this does not work correctly.

**Comment by virkt25** [comment]
The project is maintained but the team has lately been focused on LB4 development. Stalebot is configured across all our repos to keep the number of issues in check.

Would you like to open a PR to fix this issue and I can help you land it.

**Comment by CaseyMichael** [comment]
Hey @virkt25 thank you for taking the time to finally respond to my question, Im sure you are very busy on LB4. I have a few questions for you.

1. Could anyone on your team actually answer my question?
`Should having mixed transactions in loopback have the appropriate isolation?`

2. Could you pull down my sample project and see if you get the same results?

3. If the answer to #1 is `yes` then I think this should become a priority for the loopback team to fix and to prevent from happening in LB4. 

P.S. I would love to be able to make a PR and fix this issue however, I believe this is going to require someone more familiar with the code to really determine the root cause. I did some poking around but I didn't really see anything obvious.

**Comment by jannyHou** [comment]
cc @raymondfeng @bajtos do you by any chance know the expected use case of issue above ^^? 
In a transaction, do we allow calling method without specify the transaction? Like:

```
TestingTransaction.mixedTransaction = function (req) {
    // call `create` without specifying transaction
    TestingTransaction.create({value: 10})
      .then(() => {
        // call `create` with transaction
        return TestingTransaction
          .create({value: 0}, {transaction: req.transaction})
      })
      .then((timeouts) => {
        const data = _.range(500);
        return PromiseSerialMap(data, number => {
          return timeouts.updateAttributes({value: number}, {transaction: req.transaction});
        });
      })
      .catch((error) => {
        console.log(error);
        throw Error("oh no...")
      })
};
```

If we allow this use case, I will dig more into why the operation w/o transaction are not isolated.

**Comment by CaseyMichael** [comment]
@jannyHou @raymondfeng @bajtos @virkt25 Just wondering if are going to get to this issue.

**Comment by raymondfeng** [comment]
Here is how it should work:

1. If a request is executed with an active transaction (passed in `options`), it will be part of the transaction. The same connection will be used.

2. If a request is executed without an active transaction, a new connection will be acquired to run the SQL statement and autocommit will be used.

In summary, it's possible to run CRUD operations concurrently with or without a transaction.

**Comment by CaseyMichael** [comment]
@virkt25 @jannyHou @raymondfeng Is this going to be worked on?

**Comment by CaseyMichael** [comment]
@virkt25 @jannyHou @raymondfeng hello?

**Comment by CaseyMichael** [comment]
![image](https://user-images.githubusercontent.com/2779354/48290900-c980ec00-e431-11e8-865c-a29d8a072be6.png)
