### ISSUE TITLE
DataSources mysql connector returns different date then API for same item

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback-connector-mysql#354]
I'm retrieving data for the same item via both API and with datasource connector. 
The code for datasource is simple:
```
   var sqlStmt = "SELECT ......."
    var ds = app.dataSources.amysql;
    var params = [];
    ds.connector.execute(sqlStmt, params, function(err, results) {
      if (err) console.log(err);
      cb(null, results);
    });
```

The problem is that when i retrieve date via API i get:

`Date:"2018-06-09T11:04:28.000Z"` (which is correct UTC time)

but with datasource connector for same item i get:

`ActivityDate:"2018-06-09T09:04:28.000Z"`  (which is incorrect)
 
Date in the database via Phpmyadmin is `2018-06-09 11:04:28`

I tried to set `"dateStrings": ["DATE"]` or `"dateStrings":true` in datasources.json but  same thing happening.

Is there some parameter that i can pass to `ds.connector.execute` that i'm missing?

**Comment by dhmlau** [comment]
@ambrt, may i know what's your node module versions for `loopback`, `loopback-datasource-juggler` and `loopback-connector-mysql`? 

@jannyHou, does it look like it's similar to https://github.com/strongloop/loopback-datasource-juggler/issues/1577?

**Comment by ambrt** [comment]
@dhmlau versions are:
`loopback: 3.19.3`
`loopback-datasource-juggler: 3.21.1`
`loopback-connector-mysql: 5.2.0`

**Comment by ambrt** [comment]
I was old packages problem. I updated everything with `yarn upgrade --latest` and it works now. Closing.
