### ISSUE TITLE
filter where is case insensitive

### ISSUE THREAD

**Issue by josesaranda** [strongloop/loopback-connector-mysql#355]
# Description/Steps to reproduce

Im trying to apply filter where name is like %name%, but return a non expected result.
Example:
```
var filter = {where : {name : {like : '%ra%' }}};
Model.find(filter,function(err,result){
 console.log(result);
//it should return models with name matching "ra" in insensitive case
//but only returns coincidences with sensitive case, for example: "rare","radio","paragraph".
//it isn't working properly, it should return models with name matching "ra" in insensitive case, not in sensitive case
//it should return either coincidences like "Raoul","Raphael","rare","radio",...
});
```
# Additional information

Mysql where like allow insensitive case, i think the mysql-connector must allow this feature too.

**Comment by charlie-s** [comment]
Case sensitivity is defined in the column's collation settings. 

```
ALTER TABLE Model
MODIFY COLUMN name VARCHAR(…) CHARACTER
SET UTF8 COLLATE UTF8_GENERAL_CI
```

Here's some more relevant conversation on the topic: https://stackoverflow.com/questions/2876789/how-can-i-search-case-insensitive-in-a-column-using-like-wildcard/2876802

**Comment by 7ranveer** [comment]
Just a small workaround
`var filter = {where : or:[{name : {like : '%ra%' `}},{name : {like : '%Ra%' `}},{name : {like : '%RA%' `}},{name : {like : '%rA%' `}}]};`
But the correct way would be defining it in your database schema
