### ISSUE TITLE
Need to use nested query in mysql connector please provide this functionality ASAP

### ISSUE THREAD

**Issue by thatisusama** [strongloop/loopback-connector-mysql#357]
I have saved array of objects in column but now i need to apply search system in which if some object is available in any array it should return the whole row/object with matching object in array.

**Comment by charlie-s** [comment]
Is this a serialized object in a VARCHAR column, a JSON column type, or something else? You may need to just use a raw query to do this: https://loopback.io/doc/en/lb3/Executing-native-SQL.html
