### ISSUE TITLE
Querying field which is null?

### ISSUE THREAD

**Issue by SeanFacer** [strongloop/loopback-connector-mysql#364]
Hi

How can I query a field which is null? I get a a sql error

filter=[where][category_id][eq][null]

SELECT `id`,`name`,`description`,`manufacturer`,`stockcode`,`supplier_price`,`price`,`cost`,`weight`,`stock_level`,`image_url`,`path_id`,`sku`,`upc`,`ean`,`jan`,`isbn`,`stock_status_id`,`points`,`shipping`,`date_avaliable`,`weight_class_id`,`length_class_id`,`length`,`width`,`height`,`subtract`,`minimum`,`sort_order`,`tag`,`meta_title`,`meta_description`,`meta_keyword`,`image`,`image_dest`,`opencart_product_id`,`listedAmazon`,`force_update`,`discontinued`,`mpn`,`created_at`,`updated_at`,`category_id`,`supplier_id` FROM `products` WHERE `category_id`'null' ORDER BY `id`

**Comment by 7ranveer** [comment]
Hi, You can try this
Querying from Loopback
```
where: {
category_id: null
}

```Querying from MYSQL
`select * from products where category_id is null order by id`
