### ISSUE TITLE
utf8mb4  Access Token ER_TOO_LONG_KEY

### ISSUE THREAD

**Issue by YuriScarbaci** [strongloop/loopback-connector-mysql#365]
Same as in the [issue 36](https://github.com/strongloop/loopback-connector-mysql/issues/36)

the default model for AccessToken ( can be found in `node_modules/loopback/common/models/access-token.json`) doesn't define mysql max char for the id, to make the utf8mb4 charset works with the default models it's required to set the default model proprieties adding the following:
```
"id": {
   ...
      "mysql": {
        "dataType": "VARCHAR",
        "dataLength": 191
      }
},
```
defining the data length to 191.

The problem is that every time the loopback npm module is update the changes to the model are overwritten leading to problems.

Would be great if the mysql connector could detect a configuration from the `datasource.json` where we can define the dataLength for undefined varchars to avoid further problems with this issue.

**Comment by proffalken** [comment]
Can confirm changing the data length as specified above fixes the issue.

**Comment by theluk** [comment]
maybe this one can help you

https://www.npmjs.com/package/patch-package

**Comment by YuriScarbaci** [comment]
Dropped the whole loopback framework in favor of Express+sequelize+transformalizer, got more control, and working with more mature techs comes with the additional advantage of better support of postgreSQL
