### ISSUE TITLE
Rename a column deletes the existing column and creates a new column

### ISSUE THREAD

**Issue by Chandrasekarvelraj** [strongloop/loopback-connector-mysql#369]
I'm using

"loopback-connector-mysql": {
      "version": "2.4.1",
      "resolved": "http://registry.npmjs.org/loopback-connector-mysql/-/loopback-connector-mysql-2.4.1.tgz",
      "integrity": "sha1-RMH6DmXiADLYDzAKA1PhS4ZNw/Q=",
      "requires": {
        "async": "0.9.2",
        "debug": "2.6.9",
        "loopback-connector": "2.7.1",
        "mysql": "2.16.0",
        "strong-globalize": "2.10.0"
      },

Tried to rename the properties of model, from 'username' --> 'name'

It should rename the column as I expected
But it dropped the column 'username' which has data and created a new column 'name'

Is this the expected behaviour

I wanted to see this query ton be fired : 
ALTER TABLE table_name
  RENAME COLUMN old_name TO new_name;

But I saw 
ALTER TABLE `XXXX` ADD COLUMN `name` VARCHAR(512) NULL,
DROP COLUMN `username`

**Comment by abductedMind** [comment]
This is expected behavior. You should generally not "rename" columns in one step. You would create a migration to add a column, move the data, and another migration executed in the future to drop the old column once you know the data has been safely migrated.
