### ISSUE TITLE
Return and wrap client connection

### ISSUE THREAD

**Issue by pharindoko** [strongloop/loopback-connector-mysql#372]
# Description/Steps to reproduce

I would like to get AWS X-Ray solution to work with the loopback my sql connector
It wraps the mysql connection and then traces all requests made to mysql in X-Ray tool.
Description how it works:
https://www.npmjs.com/package/aws-xray-sdk-mysql

# Expected result

I can see traces for loopback and the AWS RDS mysql db in AWS X-Ray

# Additional information
If anyone has a clue how I can create the connection and pass it into the loopback mysql connector, please let me know.

**Comment by pharindoko** [comment]
Hello,

Does anyone have a clue how I can get the client connection ?

**Comment by 8secz-johndpope** [comment]
<img width="2054" alt="Screen Shot 2020-11-15 at 9 44 59 am" src="https://user-images.githubusercontent.com/50567111/99158479-403ed700-2727-11eb-90fc-fbccf2f4c930.png">

work in progress
