### ISSUE TITLE
Inconsistency while checking for transaction while acquiring and releasing connection for executing a mysql query

### ISSUE THREAD

**Issue by lavishAgrawal** [strongloop/loopback-connector-mysql#381]
Before executing any query, the connector checks for the condition, highlighed in yellow below. Since connector and connection were not being passed it always try to get a new connection from the client before executing the query.
`
**if (transaction && transaction.connection &&
   transaction.connector === this)** {
    if (debugEnabled) {
      debug('Execute SQL within a transaction');
    }
    executeWithConnection(null, transaction.connection);
  } else {
    client.getConnection(executeWithConnection);
  }
`

But, after executing the query it checks only for ‘transaction’ absence to release the connection which resolves to false if ‘transaction’ is actually present but its field (connection and connector are omitted), hence it doesn’t release the connection and waits for the transaction commit/rollback to release the connection. 
`
function handleResponse(connection, err, result) {
    **if (!transaction) {
      connection.release();
    }**
    if (err) {
      err = setHttpCode(err);
    }
    callback && callback(err, result);
  }
`

Because of the above inconsistency, in rare cases like, operating with JSON.Parse(JSON.stringify(transactionObject)), which removes '.connector' and '.connection' fields from the transaction object, it will acquire the connection because the first highlighted condition is not satisfied due to absence of 'connector' and 'connection' fields but it will not release that acquired connection because the second bold condition will resolve to false due to presence of transaction.

And, finally when it reaches the transaction end, it only closes the connection which was actually acquired while the transaction began (as transaction has reference to only one connection) and the other connection which was acquired because of above problem remains open which keeps piling up open connections in the pool and ultimately exhausts it.

I suggest to change the second condition to make it more strict and consistent with the first condition. Following is the change I suggest for the code:

`
function handleResponse(connection, err, result) {
    **if (!transaction || !transaction.connection || !transaction.connector) {
      connection.release();
    }**
    if (err) {
      err = setHttpCode(err);
    }
    callback && callback(err, result);
  }
`
Hence if it satisfies, it satisfies both highlighted condition or none.

I am raising a PR for this change.

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex ^^
