### ISSUE TITLE
Run shared tests from both v3 and v4 of juggler

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-mysql#386]
At the moment, our connectors are installing juggler 3.x to run the test suite. When we make a change to juggler@3, cis-jenkins detects downstream dependency and triggers CI build of connectors with the modified juggler version. When we make a change to juggler's master, no downstream builds are triggered.

In the past, we were maintaining multiple branches to test connectors against different juggler versions. E.g. loopback-2.x containing code from "master" but installing juggler 2.x for testing. This is rather impractical, because we don't have bandwidth to update those other branches with changes made to master.

Let's rework the connector test setup to execute tests from both juggler versions 3.x and 4.x, as we are already doing in other connector repositories.

The reference pull request to draw inspiration from: strongloop/loopback-connector-mongodb#519. See also strongloop/loopback-connector-postgresql#376.

Obviously, we need to fix the current test setup to pass on CI first, see https://github.com/strongloop/loopback-connector-mysql/issues/378

**Comment by jannyHou** [comment]
PR merged
