### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-connector-mysql#388]
Hi, what's up?

Today when wanting to connect in Loopback 4 to my MySQL database hosted in a Docker container, it has given me this error.

### Versions:
* LoopBack 4: latest
* loopback-connector-mysql: latest
* MySQL: 8.0.16

### Error
`Connection fails: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
It will be retried for the next request.
`

```
{
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol ' +
    'requested by server; consider upgrading MySQL ' +
    'client',
  sqlState: '08004',
  fatal: true
}
```

**Comment by dhmlau** [comment]
@frbuceta , i'm not sure if the error is caused by this connector.  I found this thread: https://github.com/mysqljs/mysql/issues/2046.  Could you please take a look and see if it fixes your problem? Thanks.

**Comment by frbuceta** [comment]
I'm going to check

**Comment by frbuceta** [comment]
> @frbuceta , i'm not sure if the error is caused by this connector. I found this thread: [mysqljs/mysql#2046](https://github.com/mysqljs/mysql/issues/2046). Could you please take a look and see if it fixes your problem? Thanks.

Works, thanks
