### ISSUE TITLE
Unable to Setup Websocket With Loopback4 Without using express

### ISSUE THREAD

**Issue by prth-123** [strongloop/loopback-connector-mysql#397]
I am trying to setup websocket using loopback 4 without setting up express js manually

**Comment by dhmlau** [comment]
@prth-123, could you please take a look at the example from @raymondfeng? https://github.com/raymondfeng/loopback4-example-websocket

**Comment by prth-123** [comment]
Thanks @dhmlau, I will look in this example and try to implement it as per my requirement.
