### ISSUE TITLE
dataModel.updateAttributes fails with errno 1364

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback-connector-mysql#40]
When I try to update a subset of fields in a model instance, I get errno 1364:
```
Error: ER_NO_DEFAULT_FOR_FIELD': Field 'sample' doesn't have a default value
```

Field 'sample' is not one of the fields I wish to update. The function call fails because, for MySQL, the model.save function is an alias for updateOrCreate. It generates

```
INSERT INTO <table> (<columns>) VALUES(<values>) ON DUPLICATE KEY UPDATE <col=val>...
```

The INSERT fails before it checks whether the key exists - it throws an error for any not null field not being updated.

The save function should be implemented as an unconditional update as is done in the Postgresql connector:

```
UPDATE <table>
SET <col=val>...
WHERE <id> = <idval>
```

**Comment by loay** [comment]
Issue is being resolved. 
closes #40
