### ISSUE TITLE
Multi id models with generated field not working

### ISSUE THREAD

**Issue by LonguCodes** [strongloop/loopback-connector-mysql#410]
## Steps to reproduce

Create a model with 2 fields set as id, with only one set as generated

## Current Behavior
The field is not marked as auto_increment

## Expected Behavior

The field should be marked as auto_increment

## Additional information

linux x64 10.16.3

├── @loopback/authentication@3.2.4
├── @loopback/authentication-passport@1.0.6
├── @loopback/boot@1.6.0
├── @loopback/context@1.25.0
├── @loopback/core@1.12.0
├── @loopback/openapi-v3@1.10.3
├── @loopback/repository@1.16.0
├── @loopback/rest@1.25.0
├── @loopback/rest-explorer@1.4.6
├── @loopback/service-proxy@1.3.13
├── loopback-connector-mysql@5.4.2

**Comment by agnes512** [comment]
@LonguCodes I think currently we only allow one field to be set as the id field as we don't support composite id property. If you'd like to have more than one fields to be auto-generated, you may use uuid or alter the table manually.
