### ISSUE TITLE
Bug Migration with foreign key throws

### ISSUE THREAD

**Issue by martinlierschof** [strongloop/loopback-connector-mysql#411]
After updating my project and nodejs and making some changes (boot and models) in my code my startup process started throwing in migration.js line: 1025 because modelToCheck.properties is undefined.
I suspect this is a problem with foreign keys when calling ds.autoupdate.

1.) I used to call autoupdate with a lot of datasources async before. (dont do this, somehow gets a lot mixed stuff)
2.) When an existing Foreign key exists, this will throw due the following line: var fkEntity = self.getModelDefinition(newFk.entity); because newFk.entity is the wrong key which will not be found. So basically a check for the result of fkEntity of null then drop would solve the problem.

I am currently investigating more and will update the thread why this happens.If someone can give me some details where to look, i cant roll everything back right now.

nodeversion: v13.7.0
loopback:
"loopback": "^3.26.0",
"loopback-boot": "^3.3.1",
"loopback-connector-mysql": "^5.4.2",
"loopback-datasource-juggler": "^4.18.0"

**Comment by agnes512** [comment]
Could you post your model definition? I can try to reproduce it and spot where the problem is. Thanks!

**Comment by martinlierschof** [comment]
Sorry i cannot. I produce the models on the fly from json files. i solved it by patching the mentioned line and if fkEntity is null then remove the key.

Steps to maybe reproduce:
1.) Try to create multiple models
2.) Add a foreign key with relation to another model named
3.) Try calling ds.autoupdate

then it should happen
