### ISSUE TITLE
Missing Documentation on Cascade

### ISSUE THREAD

**Issue by AlexScotland** [strongloop/loopback-connector-mysql#414]
A Co-worker of mine pointed out that each Loopback foreignKey element has an onUpdate and onDelete attribute.

Using those, we can add onDelete:"cascade", and this will add the cascade functionality built into MySQL.

No where in Loopback documentation is this mentioned, so if we can have that added, that'd be nice.

tl;dr: onDelete:"cascade" is cascade delete without any external mixins.

**Comment by agnes512** [comment]
https://github.com/strongloop/loopback-connector-mysql/issues/413
