### ISSUE TITLE
Object.nearby Function Slow and Blocking

### ISSUE THREAD

**Issue by benmarten** [strongloop/loopback-connector-mysql#45]
Hi,

I am using the nearby function for a Person class like this:

  Person.nearby = function(here, max, next) {
    max = Number(max || 10);
    Person.find({
      limit: 40,
      where: {
        location: {
          near: here,
          maxDistance: max
        }
      }
    }, next);
  };

I have almost 300 thousand persons in my database, hence the query takes around eight seconds and also blocks node in that time...

I am wondering if the calculation is done via sql or in node itself? Any advice, how to improve the performance? Adding an index on the location column does not have any effect...

**Comment by loay** [comment]
Hi @benmarten 
Is this still an issue?

**Comment by benmarten** [comment]
We are using above workaround in production, I have no idea if the implementation has been changed in the original approach...

**Comment by juancaacuna** [comment]
Hi @benmarten ! What DataType are you using on SQL for the location column?
I like your approach!

Thanks!

**Comment by benmarten** [comment]
"location": {
    "type": "geopoint",
    "required": true
  },

**Comment by alterx** [comment]
Hey, guys, for the sake of completeness, as of MySQL 5.7.6. you can use the `ST_Distance_Sphere` function which achieves the same result: 
```
  Event.nearby = function([lat, lng], distance = 5, {limit = 10, skip = 0} = {}, cb) {
    const userLocation = new GeoPoint({
      lat,
      lng,
    });

    const sql = `SELECT * from
      (SELECT *, (ST_Distance_Sphere(ST_GeomFromText('POINT(${lng} ${lat})'), location, 6373))
      AS distance FROM mydb.Event) x WHERE x.distance <= ${distance} ORDER BY distance LIMIT ${limit} OFFSET ${skip};`;

    const ds = Event.app.dataSources.db;
    const mySQLPool = ds.connector.client;
    mySQLPool.query(sql,
    function(err, rows, fields) {
      if (err) return cb(err);

      return cb(null, rows);
    });
  };
```
