### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by jcq** [strongloop/loopback-connector-mysql#46]
Does this allow for passing along settings for SSL support? If I'm understanding [this thread](https://github.com/felixge/node-mysql/issues/795) correctly, it seems that the mysql module might want an "ssl" option to be passed to it.  Is that something that is currently in place, or is that something that would have to be added to the options object in /lib/mysql.js?

**Comment by ssh24** [comment]
The SSL option can be passed through the datasource configs. Should have been fixed on this [PR](https://github.com/strongloop/loopback-connector-mysql/pull/43/files#diff-fd1940159a592c074df64da530d394e3R59). Closing this issue as a result. Feel free to reopen if needed.
