### ISSUE TITLE
Various issues when running on InnoDB engine

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mysql#49]
@raymondfeng as noted last week, a lot of the tests fail on a fresh MySQL install (5.6.20 homebrew). 

Notably errors regarding ER_TOO_LONG_KEY (almost any kind of index string column) and there seems to be a bug with isActual (the old/new data is a completely different format, causing it to always be negated - possibly related to https://github.com/strongloop/loopback/issues/468)

**Comment by loay** [comment]
Hi @fabien 
I know this is probably old, but the last patch fixed the above mentioned issues with MYSQL5.7 concerning the indexing and the long_key errors, as well as the failing test cases. 
Please take a look and let me know if you are still running into issues. Thanks.
