### ISSUE TITLE
mysql connector create method overriding default values

### ISSUE THREAD

**Issue by gdeluca** [strongloop/loopback-connector-mysql#51]
mysql connector is sending to the db unnecesary null values for fields not populated on create method, overriding the default values that should be populated otherwise by the database.
for example :  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,

to fix this on line 275 , mysql.js
if ("NULL" !== value) {
          fields.push(self.columnEscaped(model, key) + ' = ' + value);
}
note that the same is happening with  updateOrCreate.

I'll apreciate if you can commit this change, 
Regards, 
Guille

**Comment by raymondfeng** [comment]
We need to differentiate between `undefined` and `null`. If a property is set to `null`, we should pass `NULL` to MySQL. If a property is not present or `undefined`, we should skip the column. Can you create a patch?

**Comment by rnybergh** [comment]
Wouldn't the above fix remove also the values that have been explicitly set to null?

**Comment by raymondfeng** [comment]
@rnybergh That's what I'm trying to avoid.

**Comment by rnybergh** [comment]
Wouldn't this do it?
'''
if('NULL'!== value && data[key]!==undefined) {
}
'''

**Comment by ssh24** [comment]
This issue should be fixed on the latest version of the connector. The user can specify a **default** value of a property on the model definition, and the `create` method will honour the default value if the property is not specified upon the `create` request.

Here is a sample code snippet:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "required": true,
      "id": true
    },
    "role": {
      "type": "string",
      "default": "Software Developer"
    },
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mysqlDs;
  var Employee = app.models.Employee;

  db.automigrate(function(err) {
    if (err) throw err;
    Employee.create({id: 1, name: 'Bob'}, function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result, 4));
    });
  });
};
```

**console output**
```bash
sakibs-mac:mysql-51 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Created instance: { id: 1, name: 'Bob', role: 'Software Developer' }
```

**database output**
```bash
mysql> select * from Employee;
+----+--------------------+------+
| id | role               | name |
+----+--------------------+------+
|  1 | Software Developer | Bob  |
+----+--------------------+------+
```

Closing this issue as a result. Feel free to reopen if needed.
