### ISSUE TITLE
node-mysql options

### ISSUE THREAD

**Issue by cpentra1** [strongloop/loopback-connector-mysql#56]
Connection limit is being overwritten if it IS a number:

if (!isNaN(s.connectionLimit)) {
    s.connectionLimit = 10;
}

should be:

if (isNaN(s.connectionLimit)) {
    s.connectionLimit = 10;
}

without the NOT. 

line 37 loopback-connector-mysql / lib / mysql.js

**Comment by dhmlau** [comment]
Closing this issue because the PR has landed.  Thanks.
