### ISSUE TITLE
Not passing tests

### ISSUE THREAD

**Issue by amenadiel** [strongloop/loopback-connector-mysql#70]
I wanted to make a pull request to enable the creation of fulltext and spatial indexes, but the current master branch is failing the 11 tests contained in `mysql.discover.test.js`, because there isn't a STRONGLOOP database whatsoever. Perhaps we are missing a required setup file to create a dummy database?

It also fails on the index deep comparison (migration.test.js), but it might be because of convention changes in different mysql drivers. (For example, it returns a Comments and Index_comments fields, whereas the test is expecting only the former).

Can you please confirm that tests are passing on your side?

**Comment by raymondfeng** [comment]
All tests are passing on my side. A few of them require specific tables exists in the DB. We should dump the SQL scripts so that they can be set up in local DB.

**Comment by amenadiel** [comment]
@raymondfeng indeed, an SQL dump and a task to import it into a STRONGLOOP schema would be nice.

**Comment by dhmlau** [comment]
@amenadiel , closing this issue since the tests are passing.  
FYI - we've added some information in how to run tests in a docker image.  Please see: https://github.com/strongloop/loopback-connector-mysql/blob/master/README.md
