### ISSUE TITLE
No connection pooling?

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback-connector-mysql#72]
I haven't seen any documentation for connection pooling support for mysql. Is this supported in any way? I also found an old feature request from 2013 about connection pooling but I can't tell if its been implemented...

Cheers

**Comment by raymondfeng** [comment]
The connector already uses connection pooling. See https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L69

**Comment by stringbeans** [comment]
Thanks Raymond for the quick response!

**Comment by alcmontejo** [comment]
connection pooling for db2? Im having issue with buld insert.

**Comment by malek0512** [comment]
@alcmontejo you can try to change the "maxPoolSize" parameter to 1 in your vcap.json file.
See [loopback-db2-documentation](https://loopback.io/doc/en/lb3/DB2-connector.html)
