### ISSUE TITLE
Upsert() having duplicate error 1062, sqlState 23000

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-connector-mysql#73]
I have a unique use case.
I have two MySQL datasources both with almost identical tables (the new table has some optional data that can be added) and models.

I am setting up a cron to regularly upsert data from the one datasource table to the other's datasource table.

I thought I'd be able to do a find() on the old and upsert() to the new, but I get this error on updates (not inserts).

``` javascript
{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","index":0}
```

Here is the code of the function being called to do it:

``` javascript
var updateAllBoard = function () {
    server.models.Oldallboards.find({}, function (err, oldServerData) {
        if (err) {
             console.log('%j', err)
            process.exit(1);
        };
        server.models.Allboards.upsert(oldServerData, function (err, result) {
            if (err) {
                 console.log('%j', err)
                process.exit(1);
            }
            else {
                console.log('Successful transfer of board data from old to new.');
                process.exit(0);
            }
        });
    });
};

```

**Comment by alexxgathp** [comment]
The workaround I am doing is using a for loop with upsert() for each individual item. That is working, but takes long...

**Comment by raymondfeng** [comment]
I assume both model has the same PK. Can you print out the old/new instance to see what's offending? You can also run the app with `DEBUG=loopback:connector:mysql node .` to see the SQL statements.

**Comment by alexxgathp** [comment]
Yes, the same PKs. It is a temporary setup, because we're transitioning from an old PHP framework to the new Loopback framework app I built. The PHP  old system is already designed to get some necessary data regularly, so we're pulling it from there until I duplicate the feature.

I'll try out the debug and post it back here. For now, it looks like the workaround is working. 
I am using the async library to cycle through the array returned by find() and execute upsert for each.

''' javascript
var server = require('./server');
var fs = require('fs');
var async = require('async');

// Allboard data transfer from old to new
var updateAllBoard = function () {
    server.models.Oldallboards.find({}, function (err, oldServerData) {
        if (err) {
             console.log('%j', err)
            process.exit(1);
        };
        //console.log(oldServerData);

        async.eachSeries(oldServerData, server.models.Allboards.upsert.bind(server.models.Allboards), function (err, result) {
            // With the help of bind we can attach a context to the iterator before
            // passing it to async. Now the square function will be executed in its 
            // 'home' server.models.Oldallboards context.
            if (err)
                console.log(err);
            else
            console.log('Success!');
            process.exit(0);
        });

    });
};

updateAllBoard();
'''

**Comment by ssh24** [comment]
You could also use `async.each` to iterate through each of the `oldServerData` and perform an **upsert**.

Here is an example:
```js
var server = require('./server');
var async = require('async');

// Allboard data transfer from old to new
var updateAllBoard = function () {
    server.models.Oldallboards.find({}, function (err, oldServerData) {
        if (err) {
             console.log('%j', err)
            process.exit(1);
        };
        //console.log(oldServerData);

        async.each(oldServerData, function(data) {
            server.models.Allboards.upsert(data, cb);
        }, function(err) {
            if (err)
                console.log(err);
            else
                console.log('Success!');
            process.exit(0);
        });
    });
};

updateAllBoard();
```

Closing this story as resolved. Feel free to reopen if needed.
