### ISSUE TITLE
foreign key column has different dataType with its primary key

### ISSUE THREAD

**Issue by didikeke** [strongloop/loopback-connector-mysql#84]
e.g. 

if I define the pk type to string in user.json as below, it will generate  varchar(255) id column in user table, but for the other tables who has userId as foreign key column, it will generate varchar(512).
```
"properties": {
    "id": {
      "type": "string",
      "id": true
    }
  },
```

**Comment by didikeke** [comment]
or,

```
  "properties": {
    "id": {
      "type": "number",
      "dataType": "bigint",
      "id": true
    }
  }
```

Since in modern websites, it will has more than max value 2147483647 of int(11) rows data in a table in one or two years.  If it is bigint(20) from beginning, it will cost less effect in future.

However, if I set dataType as bigint, The PK will be bigint(20), but the FK will be int(11).

After searching, I found this commit : https://github.com/strongloop/loopback-datasource-juggler/commit/45154913188c09a00f06e49502227343726fc4a7
but the pkType in this commit is "string", "number", etc which are without length.


Should I define the columns' types by sql instead of the automigrate?  Or which part of codes & document I should read?

Thanks,
Echo

**Comment by raymondfeng** [comment]
I think that has been fixed by https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1712-L1717. We now also take the DB specific mapping to the FK. Can you double check?

**Comment by didikeke** [comment]
Thanks for your quick response.

This line https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1713
```
  var foreignMeta = this.columnMetadata(foreignClassName, key);
```
foreignMeta will always null,

There are two reasons:
1. key is not right value here.  It is className's column name instead of foreignClassName's column name.
e.g.  'user' has many 'userIdentity' and the foreignKey is 'userId'. 

In this line code, it is 
```
  //foreignClassName is user and key is userId in this place
  var foreignMeta = this.columnMetadata('user', 'userId');  
```

But it is not right.  It should be .columnMetadata('user', 'id');  


2. However, even if I consoled this.columnMetadata(foreignClassName, 'id') in this place, but it is still null. I still don't know why...

**Comment by didikeke** [comment]
For first reason:
the line https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1713 may need  to change from 
```
  var foreignMeta = this.columnMetadata(foreignClassName, key);

```
to 

```
  var foreignMeta = this.columnMetadata(foreignClassName, pkName);
```

for second reason, I need to understand the columnMetadata code my tomorrow. It is too late at China time now :)

**Comment by didikeke** [comment]
a)  create pull request https://github.com/strongloop/loopback-datasource-juggler/pull/498
b)  after reading https://github.com/strongloop/loopback-example-mysql:

When create string PK and make sure the FK is same dataType, the "properties" in model json file should be:

```
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "mysql": {
        "dataType": "varchar(30)" 
      }
    }
  }
```


To create bigint PK , the "properties" should be 

```
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "mysql": {
        "dataType": "bigint"
      }
    }
  }

```
