### ISSUE TITLE
MySQL Database with ACLs

### ISSUE THREAD

**Issue by ghost** [strongloop/loopback-connector-mysql#89]
Hi,

I don't find any informations about that topic but the only way i found  to use ACL with extern Database isn't really easy.

```
slc loopback:acl
```

This command allow you to add acl in model but that didn't add it in db.

That mean that we have to create all the acls with automigrate script, i think that could be cool to generate directly in db too ?

**Comment by dhmlau** [comment]
@ghost, sorry to take so long to respond. Since this problem was reported 2 years ago, closing the issue. If you're still running into this issue, feel free to reopen. Thanks.
