### ISSUE TITLE
Filter input array of numbers gets modified to array of strings

### ISSUE THREAD

**Issue by hotaru355** [strongloop/loopback-connector-mysql#93]
Possibly related to issue #65:
This is more an "annoyance" than a bug and could possibly be fixed quickly. If an array of numbers is used in a filter, it's values will get modified once used in a query:

```
var arrayOfNumbers = [1, 2];
app.models.MyModel.find({
  where: {
    myId: {
      inq: arrayOfNumbers
    }
  }, function(err, myModels) {
    console.log(typeof arrayOfNumbers[0]); // "string"
  });
```

This is annoying, if the array is required for further tasks later on. Work-around:

```
inq:arrayOfNumbers.slice()
```

Here a repo to replicate the issue: https://github.com/hotaru355/issue1287

**Comment by hotaru355** [comment]
Just found that this is a duplicate of issue #82. As opposed to the original poster, I am happy to sign your CLA, so hopefully we will see this fix soon in master.

**Comment by b-admike** [comment]
hi @hotaru355, I have verified that the issue doesn't exist following what you did in your repo (https://github.com/hotaru355/issue1287) . Can we close this issue or are you still seeing it? Can you also comment on whether https://github.com/strongloop/loopback-connector-mysql/pull/94 is needed?

**Comment by b-admike** [comment]
I have also verified #65 is not present anymore. Closing this issue and its related PR. If the issue comes up again, we can look into opening them both.
