### ISSUE TITLE
Count method throws syntax error when used with where clause

### ISSUE THREAD

**Issue by fahadtasleem** [strongloop/loopback-connector-mysql#96]
Hi,

I am trying to use where clause in count method for paginition purpose. Whenever I try to use where clause, it gives me a mysql syntax error for as simple query as below. 

Ride.count({
      where:{"id":20}
    },function(err,totalCount){
      if (err) {
        log.info("Total error ", err);
        fn(err);
      }else {
        log.info("Total count ", totalCount);
      }
    });

this is the error I get.

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '20' at line 1\n    at Query.Sequence._packetToError (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:48:14)\n    at Query.ErrorPacket (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:83:18)\n    at Protocol._parsePacket (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Protocol.js:271:23)\n    at Parser.write (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Parser.js:77:12)\n    at Protocol.write (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Protocol.js:39:16)\n    at Socket.<anonymous> (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\Connection.js:92:28)\n    at Socket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)\n    at Socket.Readable.push (_stream_readable.js:126:10)\n    at TCP.onread (net.js:529:20)\n    --------------------\n    at Protocol._enqueue (D:\\Code\\liftee\\rest-services\\node_modules\\loopback-co

**Comment by enricop89** [comment]
How did you solve it?

**Comment by debashishkumar** [comment]
How did you solve it? I also want to know

**Comment by fahadtasleem** [comment]
I was passing wrong values to count method.
Have a look at this.

http://stackoverflow.com/questions/30094144/count-method-throws-syntax-error-when-used-with-where-clause-in-loopback
