### ISSUE TITLE
Method escape has typo (esacpe) in discovery.js

### ISSUE THREAD

**Issue by fordnox** [strongloop/loopback-connector-mysql#98]
File https://github.com/strongloop/loopback-connector-mysql/blob/9dc6353b18a6cdc685b29fa64738c9df769a164c/lib/discovery.js 

Line 64 
Line 98

I receive `Object #<Object> has no method 'esacpe'` when trying to "discover models" from data source

**Comment by raymondfeng** [comment]
Good catch. Fixed and released in 2.0.1.
